<!DOCTYPE html>

<?php
ini_set('display_errors',1);
include_once('./config.php');
include_once('./user.php');
include_once('./cart.php');
include_once('./imagePathFix.php');

$userinfo = userinfo();

$cartid = cartid();

$carinfo = cart($cartid);
$carItems = $carinfo['items'];
$products = array();
foreach ($carItems as $item) {
	$product_id = $item['product_id'];
	$url= $baseHost . 'productInfo.php?ids=' . $product_id;
	$jsonResult = json_decode(file_get_contents($url),true);
	if (count($jsonResult) > 0) {
		$product = $jsonResult[0];
	}
	if (count($product['tier_price'])>0) {
		$key = array_keys($product['tier_price'])[0];
		$test = $product['tier_price'];
		$tier_price = $test[$key];
		$product['discount_price'] = round($tier_price['price'],2);
		$product['discount_count'] = round($tier_price['price_qty'],0);
	}else{
		$product['discount_price'] = round($product['price'],2);
		$product['discount_count'] = 999;
	}

	// xl add
	// 是否存在group_price
	$product['g_price'] = 0;
	if (count($product['group_price'])>0) {
		foreach ($product['group_price'] as $key => $value) {  
		    if (!is_null($value['price'])) {
				$product['g_price'] = (float)$value['price'];
				break;
			}
		} 
	}
	// xl add

	
	$product['qty'] = $item['qty'];
	array_push($products, $product);
}
?>
<html>
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no, minimal-ui"/>
	<meta name="apple-mobile-web-app-capable" content="yes"/>
	<meta name="apple-mobile-web-app-status-bar-style" content="black"/>
	<meta name="format-detection" content="telephone=no, email=no"/>
	<meta charset="UTF-8">
	<title>购物车</title>
	<link rel="stylesheet" href="themes/css/core.css">
	<link rel="stylesheet" href="themes/css/icon.css">
	<link rel="stylesheet" href="themes/css/home.css">
	<link rel="stylesheet" href="themes/css/add.css">
	<link rel="icon" type="image/x-icon" href="favicon.ico">
	<link href="iTunesArtwork@2x.png" sizes="114x114" rel="apple-touch-icon-precomposed">
	<script src="themes/js/jquery.min.js"></script>
	<script src="res/js/config.js"></script>
	<script src="themes/js/aui-car.js"></script>

	<!-- jquerWeui -->
	<link href="https://cdn.bootcss.com/weui/1.1.2/style/weui.min.css" rel="stylesheet">
	<!-- <link href="https://cdn.bootcss.com/jquery-weui/1.2.0/css/jquery-weui.min.css" rel="stylesheet"> -->
	<link href="res/css/jq-1-2-0-weui.css" rel="stylesheet">
	<script type="text/javascript" src="themes/js/jquery.min.js"></script>
	<script src="https://cdn.bootcss.com/jquery-weui/1.2.0/js/jquery-weui.min.js"></script>
</head>


<body>

	<header class="aui-header-default aui-header-fixed aui-header-bg">
		<a href="javascript:history.back(-1)" class="aui-header-item">
			<i class="aui-icon aui-icon-back-white"></i>
		</a>
		<div class="aui-header-center aui-header-center-clear">
			<div class="aui-header-center-logo">
				<div class="aui-car-white-Typeface">购物车<?php //echo $cartid; ?></div>
			</div>
		</div>
		<a href="kefu.html" class="aui-header-item-icon"   style="color: #fff;font-size: 16px;">
			<!-- <i class="aui-icon aui-icon-member"></i> -->
			客服
		</a>
	</header>
	<section class="aui-car-content">
		<div class="aui-car-box">
			<div class="aui-car-box-user-group-id" style="display:none">
				<?php 
					if (!is_null($userinfo)) {
						echo $userinfo['group_id']; 
					}
				?>
			</div>

<!-- 			<div class="aui-car-box-name">
				<input type="checkbox" class="check goods-check shopCheck">
				<h3>
					<a href="#">全选</a>
				</h3>
				<div class="aui-car-coupons">
					<a href="#">领券</a>
					<a href="#">编辑</a>
				</div>
			</div> -->
			<div class="aui-car-box-list">
				<ul>
<!-- 					<li>
						<div class="aui-car-box-list-item">
							<input type="checkbox" class="check goods-check goodsCheck">
							<div class="aui-car-box-list-img">
								<a href="ui-product.phtml">
									<img src="themes/img/pd/sf-1.jpg" alt="">
								</a>
							</div>
							<div class="aui-car-box-list-text">
								<h4>
									<a href="ui-product.phtml">【黑卡96折】Apple 苹果 iPhone 7（A1660）移动联通电信4G手机 国内行货</a>
								</h4>
								<div class="aui-car-box-list-text-brief">
									<span>重量:3.3kg</span>
									<span>颜色:标配版</span>
									<span>版本:5.7英寸</span>
								</div>
								<div class="aui-car-box-list-text-price">
									<div class="aui-car-box-list-text-pri">
										￥<b class="price">100.00</b>
									</div>
									<div class="aui-car-box-list-text-arithmetic">
										<a href="javascript:;" class="minus">-</a>
										<span class="num">1</span>
										<a href="javascript:;" class="plus">+</a>
									</div>
								</div>
							</div>

						</div>
					</li> -->
					<?php foreach ($products as $item) {
					?>
					<li>
						<div class="aui-car-box-list-item">
							<div class="aui-car-box-list-item-g-price" style="display:none"><?php echo $item['g_price'] ?></div>
							<div class="aui-car-box-list-item-discount-price" style="display:none"><?php echo $item['discount_price'] ?></div>
							<div class="aui-car-box-list-item-discount-count" style="display:none"><?php echo $item['discount_count']?></div>
							<div class="aui-car-box-list-item-origin-price" style="display:none">
							<?php
								// 有特价显示特价
								if (!is_null($item['special_price'])) {
									$special_price = round($item['special_price'],2);
									echo $special_price;	
								}else{
									echo number_format($item['price'],2);	
								}
							?>
							</div>
							<input style="display:none" type="checkbox" class="check goods-check goodsCheck" checked="checked">
							<div class="aui-car-box-list-img">
								<a href="ui-product.phtml?productId=<?php echo $item['product_id']; ?>">
									<div class="class_img_box">
									<img src="<?php echo smallImage($item['image']) ?>" alt="">
									</div>
								</a>
							</div>
							<div class="aui-car-box-list-text">
								<h4>
									<a href="ui-product.phtml?productId=<?php echo $item['product_id']; ?>"><?php echo $item['name'];  ?></a>
								</h4>
								<div class="aui-car-box-list-text-brief">
									<span><?php echo $item['short_description']; ?></span>
								</div>
								<div style="display:none" class="prodcut_id"><?php echo $item['product_id'];  ?></div>
								<div class="aui-car-box-list-text-price">
									<div class="aui-car-box-list-text-pri">
										CA$<b class="price">&nbsp;&nbsp;
										<?php 
											// 最终用户可见价格
											if (!is_null($item['special_price'])) {
												$special_price = round($item['special_price'],2);
												echo $special_price;	
											}else{
												echo number_format($item['price'],2);	
											}
										?></b>
									</div>
									<div class="aui-car-box-list-text-arithmetic">
										<a href="javascript:;" class="minus">-</a>
										<span class="num"><?php echo $item['qty']; ?></span>
										
										<div style="display:none" class="min_prodcut_id"><?php echo $item['product_id'];  ?></div>
										<a href="javascript:;" class="plus">+</a>
									</div>
								</div>
							</div>

						</div>
					</li>

					<?php } ?>


				</ul>
			</div>
			<div class="aui-shopPrice">
				本店总计:CA$
				<span class="aui-total-amount ShopTotal">00.00</span>
			</div>
		</div>
	</section>
	<div class="aui-payment-bar">
		<!-- <div class="all-checkbox"><input type="checkbox" class="check goods-check" id="AllCheck">全选</div> -->
		<div class="shop-total">
			<strong>合计：<i class="total" id="AllTotal">00.00</i></strong>
			<div style="display:none" class="cart_id"><?php echo $this->cartid;  ?></div>
		</div>
		<?php echo '<a href="javascript:void(0);" class="settlement" onclick="updatecart(\''.$cartid.'\')">结算</a>'; ?>
	</div>

<script type="text/javascript">

 function updatecart(cartid) { 

 		var datas = [];
	    $(".aui-car-box").each(function() { //循环每个店铺
	      $(this).find(".goodsCheck").each(function() { //循环店铺里面的商品
            var num = parseInt($(this).parents(".aui-car-box-list-item").find(".num").text()); //得到商品的数量
            var productid = parseFloat($(this).parents(".aui-car-box-list-item").find(".prodcut_id").text()); 
            var dict = {};
            dict.product_id = productid;
            dict.qty = num;
            datas.push(dict);
	      });
	    });
	    if (datas.length == 0) {
	    	alert('购物车空空，去添加商品吧~');
	    	return;
	    };
	    var str = JSON.stringify(datas);
        $.ajax({  
            url: "<?php echo $baseHost ?>cart.php?cartid="+cartid+"&updateCart="+str,           
            type: "GET",         
            success:function(result){  
            	if (result == "true") {
            		window.location.href=  '<?php echo $baseHost ?>order-sure.phtml';
            	}else{
            		alert('网络错误，请重试');
            	};
                // $('#loading').hideLoading();
                // document.location.reload(); 
            },
            error:function(XMLHttpRequest, textStatus, errorThrown){
                // $('#loading').hideLoading();
                alert('网络错误，请重试');
            }
        });
    }

</script>
</body>
</html>