<!DOCTYPE html>

<?php
ini_set('display_errors',1);
include_once('./user.php');
include_once('./cart.php');
include_once('./imagePathFix.php');

// 许雷测试
// include_once('./test.php');
// $userid = userid();
// $cartid = null;
// if ($userid == null) {
// 	// 用户未登录，使用本地原来购物车
// 	$cartid = cartid();
// }else{
// 	// 用户已登录，获取PC端购物车并检查是否可用
// 	$cartid = getCartIdByUser($userid);
// 	// PC购物车信息
// 	$cartInfo = cart($cartid);
// 	if($cartInfo['payment'] != null && $cartInfo['payment']['payment_id'] != null){
// 		// PC端购车不可用，使用本地购物车
// 		$cartid = cartid();
// 	}
// }
// 许雷测试

$cartid = cartid();


$carinfo = cart($cartid);
$carItems = $carinfo['items'];
$products = array();
foreach ($carItems as $item) {
	$product_id = $item['product_id'];
	$url='https://m.bdbbuy.com/productInfo.php?ids='.$product_id;
	$jsonResult = json_decode(file_get_contents($url),true);
	if (count($jsonResult) > 0) {
		$product = $jsonResult[0];
	}
	if (count($product['tier_price'])>0) {
		$key = array_keys($product['tier_price'])[0];
		$test = $product['tier_price'];
		$tier_price = $test[$key];
		$product['discount_price'] = round($tier_price['price'],2);
		$product['discount_count'] = round($tier_price['price_qty'],0);
	}else{
		$product['discount_price'] = round($product['price'],2);
		$product['discount_count'] = 999;
	}
	$product['qty'] = $item['qty'];
	array_push($products, $product);
}


?>
<html>
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no, minimal-ui"/>
	<meta name="apple-mobile-web-app-capable" content="yes"/>
	<meta name="apple-mobile-web-app-status-bar-style" content="black"/>
	<meta name="format-detection" content="telephone=no, email=no"/>
	<meta charset="UTF-8">
	<title>购物车</title>
	<link rel="stylesheet" href="themes/css/core.css">
	<link rel="stylesheet" href="themes/css/icon.css">
	<link rel="stylesheet" href="themes/css/home.css">
	<link rel="stylesheet" href="themes/css/add.css">
	<link rel="icon" type="image/x-icon" href="favicon.ico">
	<link href="iTunesArtwork@2x.png" sizes="114x114" rel="apple-touch-icon-precomposed">
	<script src="themes/js/jquery.min.js"></script>
	<script src="themes/js/aui-car.js"></script>
</head>

<script type="text/javascript">

 function updatecart(cartid) { 

 		var datas = [];
	    $(".aui-car-box").each(function() { //循环每个店铺
	      $(this).find(".goodsCheck").each(function() { //循环店铺里面的商品
            var num = parseInt($(this).parents(".aui-car-box-list-item").find(".num").text()); //得到商品的数量
            var productid = parseFloat($(this).parents(".aui-car-box-list-item").find(".prodcut_id").text()); 
            var dict = {};
            dict.product_id = productid;
            dict.qty = num;
            datas.push(dict);
	      });
	    });
	    if (datas.length == 0) {
	    	alert('购物车空空，去添加商品吧~');
	    	return;
	    };
	    var str = JSON.stringify(datas);
        $.ajax({  
            url:"https://m.bdbbuy.com/cart.php?cartid="+cartid+"&updateCart="+str,           
            type: "GET",         
            success:function(result){  
            	if (result == "true") {
            		window.location.href='https://m.bdbbuy.com/order-sure.phtml';
            	}else{
            		alert('网络错误，请重试');
            	};
                // $('#loading').hideLoading();
                // document.location.reload(); 
            },
            error:function(XMLHttpRequest, textStatus, errorThrown){
                // $('#loading').hideLoading();
                alert('网络错误，请重试');
            }
        });
    }

</script>
<body>

	<header class="aui-header-default aui-header-fixed aui-header-bg">
		<a href="javascript:history.back(-1)" class="aui-header-item">
			<i class="aui-icon aui-icon-back-white"></i>
		</a>
		<div class="aui-header-center aui-header-center-clear">
			<div class="aui-header-center-logo">
				<div class="aui-car-white-Typeface">购物车<?php //echo $cartid; ?></div>
			</div>
		</div>
		<a href="kefu.html" class="aui-header-item-icon"   style="color: #fff;font-size: 16px;">
			<!-- <i class="aui-icon aui-icon-member"></i> -->
			客服
		</a>
	</header>
	<section class="aui-car-content">
		<div class="aui-car-box">
<!-- 			<div class="aui-car-box-name">
				<input type="checkbox" class="check goods-check shopCheck">
				<h3>
					<a href="#">全选</a>
				</h3>
				<div class="aui-car-coupons">
					<a href="#">领券</a>
					<a href="#">编辑</a>
				</div>
			</div> -->
			<div class="aui-car-box-list">
				<ul>
<!-- 					<li>
						<div class="aui-car-box-list-item">
							<input type="checkbox" class="check goods-check goodsCheck">
							<div class="aui-car-box-list-img">
								<a href="ui-product.phtml">
									<img src="themes/img/pd/sf-1.jpg" alt="">
								</a>
							</div>
							<div class="aui-car-box-list-text">
								<h4>
									<a href="ui-product.phtml">【黑卡96折】Apple 苹果 iPhone 7（A1660）移动联通电信4G手机 国内行货</a>
								</h4>
								<div class="aui-car-box-list-text-brief">
									<span>重量:3.3kg</span>
									<span>颜色:标配版</span>
									<span>版本:5.7英寸</span>
								</div>
								<div class="aui-car-box-list-text-price">
									<div class="aui-car-box-list-text-pri">
										￥<b class="price">100.00</b>
									</div>
									<div class="aui-car-box-list-text-arithmetic">
										<a href="javascript:;" class="minus">-</a>
										<span class="num">1</span>
										<a href="javascript:;" class="plus">+</a>
									</div>
								</div>
							</div>

						</div>
					</li> -->
					<?php foreach ($products as $item) {
					?>
					<li>
						<div class="aui-car-box-list-item">
							<div class="aui-car-box-list-item-discount-price" style="display:none"><?php echo $item['discount_price'] ?></div>
							<div class="aui-car-box-list-item-discount-count" style="display:none"><?php echo $item['discount_count']?></div>
							<div class="aui-car-box-list-item-origin-price" style="display:none">
							<?php
								if (!is_null($item['special_price'])) {
									$special_price = round($item['special_price'],2);
									echo $special_price;	
								}else{
									echo number_format($item['price'],2);	
								}
							?>
							</div>
							<input style="display:none" type="checkbox" class="check goods-check goodsCheck" checked="checked">
							<div class="aui-car-box-list-img">
								<a href="ui-product.phtml?productId=<?php echo $item['product_id']; ?>">
									<div class="class_img_box">
									<img src="<?php echo smallImage($item['image']) ?>" alt="">
									</div>
								</a>
							</div>
							<div class="aui-car-box-list-text">
								<h4>
									<a href="ui-product.phtml?productId=<?php echo $item['product_id']; ?>"><?php echo $item['name'];  ?></a>
								</h4>
								<div class="aui-car-box-list-text-brief">
									<span><?php echo $item['short_description']; ?></span>
								</div>
								<div style="display:none" class="prodcut_id"><?php echo $item['product_id'];  ?></div>
								<div class="aui-car-box-list-text-price">
									<div class="aui-car-box-list-text-pri">
										CAd$<b class="price">&nbsp;&nbsp;
										<?php 
											if (!is_null($item['special_price'])) {
												$special_price = round($item['special_price'],2);
												echo $special_price;	
											}else{
												echo number_format($item['price'],2);	
											}
											
										?></b>
									</div>
									<div class="aui-car-box-list-text-arithmetic">
										<a href="javascript:;" class="minus">-</a>
										<span class="num"><?php echo $item['qty']; ?></span>
										<div style="display:none" class="cart_id"><?php echo $cartid;  ?></div>
										<div style="display:none" class="min_prodcut_id"><?php echo $item['product_id'];  ?></div>
										<a href="javascript:;" class="plus">+</a>
									</div>
								</div>
							</div>

						</div>
					</li>

					<?php } ?>


				</ul>
			</div>
			<div class="aui-shopPrice">
				本店总计:CA$
				<span class="aui-total-amount ShopTotal">00.00</span>
			</div>
		</div>
	</section>
	<div class="aui-payment-bar">
		<!-- <div class="all-checkbox"><input type="checkbox" class="check goods-check" id="AllCheck">全选</div> -->
		<div class="shop-total">
			<strong>合计：<i class="total" id="AllTotal">00.00</i></strong>
		</div>
		<?php echo '<a href="javascript:void(0);" class="settlement" onclick="updatecart(\''.$cartid.'\')">结算</a>'; ?>
	</div>


</body>
</html>