<!DOCTYPE html>
<html>
<head>
	<title>找回密码/重置密码</title>
	<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no, minimal-ui"/>
	<meta name="apple-mobile-web-app-capable" content="yes"/>
	<meta name="apple-mobile-web-app-status-bar-style" content="black"/>
	<meta name="format-detection" content="telephone=no, email=no"/>
	<meta charset="UTF-8">
	<link rel="icon" type="image/x-icon" href="favicon.ico">
	<link href="iTunesArtwork@2x.png" sizes="114x114" rel="apple-touch-icon-precomposed">
	<link rel="stylesheet" href="themes/css/core.css">
	<link rel="stylesheet" href="themes/css/icon.css">
	<link rel="stylesheet" href="themes/css/home.css">

	<!-- jquerWeui -->
	<link href="https://cdn.bootcss.com/weui/1.1.2/style/weui.min.css" rel="stylesheet">
	<!-- <link href="https://cdn.bootcss.com/jquery-weui/1.2.0/css/jquery-weui.min.css" rel="stylesheet"> -->
	<link href="res/css/jq-1-2-0-weui.css" rel="stylesheet">
</head>
<?php
	$tip = $_GET['tip'];
?>
<body>
	<header class="aui-header-default aui-header-fixed aui-header-bg">
		<a href="javascript:history.back(-1)" class="aui-header-item">
			<i class="aui-icon aui-icon-back-white"></i>
		</a>
		<div class="aui-header-center">
			<div class="aui-header-center-logo">
				<div class="aui-car-white-Typeface"><?php echo $tip; ?></div>
			</div>
		</div>
	</header>

	<div class="weui-msg" style="margin-top:50px;">
		<div class="weui-cells__title" style="text-align: left;font-size: 16px;">请在下面输入你的电子邮件地址。你将收到一个重置密码的链接。</div>
		<div class="weui-cells">
		  <div class="weui-cell">
		    <div class="weui-cell__bd">
		      <input class="weui-input" id = "email" type="text" placeholder="请输入邮箱">
		    </div>
		  </div>
		</div>

	  	<a href="#" onclick="sendEmail()" class="weui-btn weui-btn_primary" style="background-color: #ed3e6e;width: 80%;margin-top: 20px;">提交</a>

	  	<!-- 底部 -->
	  	<div class="weui-msg__extra-area">
		    <div class="weui-footer">
		      <p class="weui-footer__links">
		        <a href="javascript:void(0);" class="weui-footer__link">八点半买</a>
		      </p>
		      <p class="weui-footer__text">Copyright © 2008-2017 bdbbuy</p>
		    </div>
	  	</div>
	</div>

	<script type="text/javascript" src="themes/js/jquery.min.js"></script>
	<script src="https://cdn.bootcss.com/jquery-weui/1.2.0/js/jquery-weui.min.js"></script>
	<script type="text/javascript" src="res/js/config.js"></script>
	<script type="text/javascript" src="res/js/check.js"></script>
	<script type="text/javascript" src="res/js/getPassword.js"></script>

</body>
</html>