<!DOCTYPE html>

<html lang="en">
<head>
	<meta http-equiv="pragma" content="public" />
	<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no, minimal-ui"/>
	<meta name="apple-mobile-web-app-capable" content="yes"/>
	<meta name="apple-mobile-web-app-status-bar-style" content="black"/>
	<meta name="format-detection" content="telephone=no, email=no"/>
	<meta charset="UTF-8">
	<title>八点半买</title>
	<link rel="stylesheet" type="text/css" href="themes/css/core.css">
	<link rel="stylesheet" type="text/css" href="themes/css/icon.css">
	<link rel="stylesheet" type="text/css" href="themes/css/home.css">
	<link rel="icon" type="image/x-icon" href="favicon.ico">
	<link href="iTunesArtwork@2x.png" sizes="114x114" rel="apple-touch-icon-precomposed">
</head>
<body>

	<header class="aui-header-default aui-header-fixed aui-header-bg">
		<a href="#" class="aui-header-item"  style="display:none">
			<i class="aui-icon aui-icon-code"></i>
		</a>
		<div class="aui-header-center aui-header-center-clear">
			<div class="aui-header-search-box">
				<i class="aui-icon aui-icon-small-search"></i>
				<input id="" type="text"  placeholder="请输入搜索关键字" class="aui-header-search">
			</div>
		</div>
		<a href="#" class="aui-header-item-icon">
			<i class="aui-icon aui-icon-packet" style="display:none"></i>
			<i class="aui-icon aui-icon-member" style="display:none"></i>
		</a>
	</header>
	<div class="aui-content-box">
		<div class="aui-banner-content aui-fixed-top" data-aui-slider>
			<div class="aui-banner-wrapper">
				<div class="aui-banner-wrapper-item">
					<a href="#">
						<img src="themes/img/bg/bg-s1-01.png">
					</a>
				</div>
				<div class="aui-banner-wrapper-item">
					<a href="#">
						<img src="themes/img/bg/bg-s2-01.png">
					</a>
				</div>
				<div class="aui-banner-wrapper-item">
					<a href="#">
						<img src="themes/img/bg/bg-s3-01.png">
					</a>
				</div>
				<div class="aui-banner-wrapper-item">
					<a href="#">
						<img src="themes/img/bg/bg-s4-01.png">
					</a>
				</div>
			</div>
			<div class="aui-banner-pagination"></div>
		</div>
		<section class="aui-grid-content">
			<div class="aui-grid-row" id="category">
				<a href="my-sign.html" class="aui-grid-row-item"><i class="aui-icon-large aui-icon-256"></i><p class="aui-grid-row-label">生鲜水果</p></a>
				<a href="my-sign.html" class="aui-grid-row-item"><i class="aui-icon-large aui-icon-64"></i><p class="aui-grid-row-label">休闲零食</p></a>
				<a href="my-sign.html" class="aui-grid-row-item"><i class="aui-icon-large aui-icon-79"></i><p class="aui-grid-row-label">饼干糕点</p></a>
				<a href="my-sign.html" class="aui-grid-row-item"><i class="aui-icon-large aui-icon-92"></i><p class="aui-grid-row-label">糖果巧克力</p></a>
				<a href="my-sign.html" class="aui-grid-row-item"><i class="aui-icon-large aui-icon-128"></i><p class="aui-grid-row-label">坚果蜜饯</p></a>

				<a href="my-sign.html" class="aui-grid-row-item"><i class="aui-icon-large aui-icon-141"></i><p class="aui-grid-row-label">粮油调味</p></a>
				<a href="my-sign.html" class="aui-grid-row-item"><i class="aui-icon-large aui-icon-135"></i><p class="aui-grid-row-label">酒水饮料</p></a>
				<a href="my-sign.html" class="aui-grid-row-item"><i class="aui-icon-large aui-icon-113"></i><p class="aui-grid-row-label">方便速食</p></a>
				<a href="my-sign.html" class="aui-grid-row-item"><i class="aui-icon-large aui-icon-122"></i><p class="aui-grid-row-label">个人护理</p></a>
				<a href="my-sign.html" class="aui-grid-row-item"><i class="aui-icon-large aui-icon-163"></i><p class="aui-grid-row-label">生活日用</p></a>

			</div>
		</section>
		<!-- <div class="aui-avd-content clearfix">
			<a href="#">
				<img src="themes/img/pd/cf-1.jpg" alt="">
			</a>
			<a href="#">
				<img src="themes/img/pd/cf-3.jpg" alt="">
			</a>
		</div>
		<div class="aui-slide-box aui-slide-box-clear">
			<div class="aui-slide-list">
				<ul class="aui-slide-item-list">
					<li class="aui-slide-item-item">
						<a href="#" class="v-link">
							<img class="v-img" src="themes/img/ad/tou-1.jpg">
						</a>
					</li>
					<li class="aui-slide-item-item">
						<a href="#" class="v-link">
							<img class="v-img" src="themes/img/ad/tou-2.jpg">
						</a>
					</li>
					<li class="aui-slide-item-item">
						<a href="#" class="v-link">
							<img class="v-img" src="themes/img/ad/tou-3.jpg">
						</a>
					</li>
					<li class="aui-slide-item-item">
						<a href="#" class="v-link">
							<img class="v-img" src="themes/img/ad/tou-4.jpg">
						</a>
					</li>
					<li class="aui-slide-item-item">
						<a href="#" class="v-link">
							<img class="v-img" src="themes/img/ad/tou-5.jpg">
						</a>
					</li>
					<li class="aui-slide-item-item">
						<a href="#" class="v-link">
							<img class="v-img" src="themes/img/ad/tou-6.jpg">
						</a>
					</li>
				</ul>
			</div>

		</div> -->
		<div class="aui-dri"></div>
		<div class="aui-list-content">
			<div class="aui-list-item">
				<div class="aui-list-item-img">
					<img src="themes/img/pd/cf-4.jpg" alt="">
				</div>
				<div class="aui-slide-box">
					<div class="aui-slide-list">
						<ul class="aui-slide-item-list" id = "fruit">
<!-- 							<li class="aui-slide-item-item">
								<a href="ui-product.html" class="v-link">
									<img class="v-img" src="themes/img/pd/pd-zf-5.jpg">
									<p class="aui-slide-item-title aui-slide-item-f-els">茵曼2017秋装新款小清新文艺圆领长袖条纹针织衫女套</p>
									<p class="aui-slide-item-info">
										<span class="aui-slide-item-price">¥249</span>&nbsp;&nbsp;<span class="aui-slide-item-mrk">¥499</span>
									</p>
								</a>
							</li>
							<li class="aui-slide-item-item">
								<a href="ui-product.html" class="v-link">
									<img class="v-img" src="themes/img/pd/sf-9.jpg">
									<p class="aui-slide-item-title aui-slide-item-f-els">科克兰 盐焗烘烤开心果 1.36千克</p>
									<p class="aui-slide-item-info">
										<span class="aui-slide-item-price">¥99</span>&nbsp;&nbsp;<span class="aui-slide-item-mrk">¥198</span>
									</p>
								</a>
							</li>
							<li class="aui-slide-item-item">
								<a href="ui-product.html" class="v-link">
									<img class="v-img" src="themes/img/pd/sf-10.jpg">
									<p class="aui-slide-item-title aui-slide-item-f-els">榙榙 咸鸭蛋黄饼干 80克/袋</p>
									<p class="aui-slide-item-info">
										<span class="aui-slide-item-price">¥12.9</span>&nbsp;&nbsp;<span class="aui-slide-item-mrk">¥49</span>
									</p>
								</a>
							</li>
							<li class="aui-slide-item-item">
								<a href="ui-product.html" class="v-link">
									<img class="v-img" src="themes/img/pd/sf-11.jpg">
									<p class="aui-slide-item-title aui-slide-item-f-els">唯他可可 椰子水饮料 330毫升/盒 12盒</p>
									<p class="aui-slide-item-info">
										<span class="aui-slide-item-price">¥189</span>&nbsp;&nbsp;<span class="aui-slide-item-mrk">¥299</span>
									</p>
								</a>
							</li>
							<li class="aui-slide-item-item">
								<a href="ui-product.html" class="v-link">
									<img class="v-img" src="themes/img/pd/sf-12.jpg">
									<p class="aui-slide-item-title aui-slide-item-f-els">巴黎水 含气青柠味饮料 330毫升 24</p>
									<p class="aui-slide-item-info">
										<span class="aui-slide-item-price">¥129</span>&nbsp;&nbsp;<span class="aui-slide-item-mrk">¥199</span>
									</p>
								</a>
							</li>
							<li class="aui-slide-item-item">
								<a href="ui-product.html" class="v-link">
									<img class="v-img" src="themes/img/pd/sf-13.jpg">
									<p class="aui-slide-item-title aui-slide-item-f-els">calbee 卡乐比 日本进口休闲零食佳可比黄油味薯条 90克/盒</p>
									<p class="aui-slide-item-info">
										<span class="aui-slide-item-price">¥19.9</span>&nbsp;&nbsp;<span class="aui-slide-item-mrk">¥49</span>
									</p>
								</a>
							</li> -->
						</ul>
					</div>
				</div>
			</div>
		</div>
		<div class="aui-list-item">
<!-- 			<div class="aui-list-item-img">
				<img src="themes/img/pd/cf-5.jpg" alt="">
			</div> -->
			<div class="aui-slide-box">
				<div class="aui-slide-list">
					<ul class="aui-slide-item-list">
						<li class="aui-slide-item-item">
							<a href="ui-product.html" class="v-link">
								<img class="v-img" src="themes/img/pd/sf-15.jpg">
								<p class="aui-slide-item-title aui-slide-item-f-els">Whoo 后 秘贴焕然新生精华液护肤礼盒 精华45毫升</p>
								<p class="aui-slide-item-info">
									<span class="aui-slide-item-price">¥349</span>&nbsp;&nbsp;<span class="aui-slide-item-mrk">¥499</span>
								</p>
							</a>
						</li>
						<li class="aui-slide-item-item">
							<a href="ui-product.html" class="v-link">
								<img class="v-img" src="themes/img/pd/sf-16.jpg">
								<p class="aui-slide-item-title aui-slide-item-f-els">Sulwhasoo 雪花秀 润燥精华60毫升</p>
								<p class="aui-slide-item-info">
									<span class="aui-slide-item-price">¥99</span>&nbsp;&nbsp;<span class="aui-slide-item-mrk">¥198</span>
								</p>
							</a>
						</li>
						<li class="aui-slide-item-item">
							<a href="ui-product.html" class="v-link">
								<img class="v-img" src="themes/img/pd/sf-17.jpg">
								<p class="aui-slide-item-title aui-slide-item-f-els">雅诗兰黛 红石榴护肤三件套  红色正能</p>
								<p class="aui-slide-item-info">
									<span class="aui-slide-item-price">¥399</span>&nbsp;&nbsp;<span class="aui-slide-item-mrk">¥999</span>
								</p>
							</a>
						</li>
						<li class="aui-slide-item-item">
							<a href="#" class="v-link">
								<img class="v-img" src="themes/img/pd/sf-18.jpg">
								<p class="aui-slide-item-title aui-slide-item-f-els">Whoo 后 拱辰享水 水妍护肤套装 </p>
								<p class="aui-slide-item-info">
									<span class="aui-slide-item-price">¥189</span>&nbsp;&nbsp;<span class="aui-slide-item-mrk">¥299</span>
								</p>
							</a>
						</li>
						<li class="aui-slide-item-item">
							<a href="ui-product.html" class="v-link">
								<img class="v-img" src="themes/img/pd/sf-19.jpg">
								<p class="aui-slide-item-title aui-slide-item-f-els">惊喜水分套装 持续补水维持平衡</p>
								<p class="aui-slide-item-info">
									<span class="aui-slide-item-price">¥1349</span>&nbsp;&nbsp;<span class="aui-slide-item-mrk">¥4199</span>
								</p>
							</a>
						</li>
					</ul>
				</div>

			</div>
			</div>
			<div class="aui-list-item">
				<div class="aui-list-item-img">
					<img src="themes/img/pd/cf-7.jpg" alt="">
				</div>
				<div class="aui-slide-box">
					<div class="aui-slide-list">
						<ul class="aui-slide-item-list">
							<li class="aui-slide-item-item">
								<a href="ui-product.html" class="v-link">
									<img class="v-img" src="themes/img/pd/sf-25.jpg">
									<p class="aui-slide-item-title aui-slide-item-f-els">LA 女士宽松毛衣纯色针织衫外套长袖上衣</p>
									<p class="aui-slide-item-info">
										<span class="aui-slide-item-price">¥249</span>&nbsp;&nbsp;<span class="aui-slide-item-mrk">¥499</span>
									</p>
								</a>
							</li>
							<li class="aui-slide-item-item">
								<a href="ui-product.html" class="v-link">
									<img class="v-img" src="themes/img/pd/sf-26.jpg">
									<p class="aui-slide-item-title aui-slide-item-f-els">FIRSTMIX秋季新款宽松圆领女式针织开衫</p>
									<p class="aui-slide-item-info">
										<span class="aui-slide-item-price">¥99</span>&nbsp;&nbsp;<span class="aui-slide-item-mrk">¥198</span>
									</p>
								</a>
							</li>
							<li class="aui-slide-item-item">
								<a href="ui-product.html" class="v-link">
									<img class="v-img" src="themes/img/pd/sf-27.jpg">
									<p class="aui-slide-item-title aui-slide-item-f-els">maxwin 马威 女式八分袖针织连衣裙</p>
									<p class="aui-slide-item-info">
										<span class="aui-slide-item-price">¥122.9</span>&nbsp;&nbsp;<span class="aui-slide-item-mrk">¥149</span>
									</p>
								</a>
							</li>
							<li class="aui-slide-item-item">
								<a href="ui-product.html" class="v-link">
									<img class="v-img" src="themes/img/pd/sf-28.jpg">
									<p class="aui-slide-item-title aui-slide-item-f-els">唯他可可 椰子水饮料 330毫升/盒 12盒</p>
									<p class="aui-slide-item-info">
										<span class="aui-slide-item-price">¥189</span>&nbsp;&nbsp;<span class="aui-slide-item-mrk">¥299</span>
									</p>
								</a>
							</li>
							<li class="aui-slide-item-item">
								<a href="ui-product.html" class="v-link">
									<img class="v-img" src="themes/img/pd/sf-29.jpg">
									<p class="aui-slide-item-title aui-slide-item-f-els">巴黎水 含气青柠味饮料 330毫升 24</p>
									<p class="aui-slide-item-info">
										<span class="aui-slide-item-price">¥129</span>&nbsp;&nbsp;<span class="aui-slide-item-mrk">¥199</span>
									</p>
								</a>
							</li>
							<li class="aui-slide-item-item">
								<a href="ui-product.html" class="v-link">
									<img class="v-img" src="themes/img/pd/sf-30.jpg">
									<p class="aui-slide-item-title aui-slide-item-f-els">calbee 卡乐比 日本进口休闲零食佳可比黄油味薯条 90克/盒</p>
									<p class="aui-slide-item-info">
										<span class="aui-slide-item-price">¥19.9</span>&nbsp;&nbsp;<span class="aui-slide-item-mrk">¥49</span>
									</p>
								</a>
							</li>
						</ul>
					</div>

				</div>
			</div>
			<div class="aui-list-item">
				<div class="aui-list-item-img">
					<img src="themes/img/pd/cf-6.jpg" alt="">
				</div>
				<div class="aui-slide-box">
					<div class="aui-slide-list">
						<ul class="aui-slide-item-list">
							<li class="aui-slide-item-item">
								<a href="ui-product.html" class="v-link">
									<img class="v-img" src="themes/img/pd/sf-20.jpg">
									<p class="aui-slide-item-title aui-slide-item-f-els">nissen 凹凸纵横弹性沙发套</p>
									<p class="aui-slide-item-info">
										<span class="aui-slide-item-price">¥31149</span>&nbsp;&nbsp;<span class="aui-slide-item-mrk">¥11499</span>
									</p>
								</a>
							</li>
							<li class="aui-slide-item-item">
								<a href="ui-product.html" class="v-link">
									<img class="v-img" src="themes/img/pd/sf-21.jpg">
									<p class="aui-slide-item-title aui-slide-item-f-els">日本NITORI尼达利 三折坐垫 长毛条纹 浅棕 </p>
									<p class="aui-slide-item-info">
										<span class="aui-slide-item-price">¥1199</span>&nbsp;&nbsp;<span class="aui-slide-item-mrk">¥1198</span>
									</p>
								</a>
							</li>
							<li class="aui-slide-item-item">
								<a href="ui-product.html" class="v-link">
									<img class="v-img" src="themes/img/pd/sf-22.jpg">
									<p class="aui-slide-item-title aui-slide-item-f-els">商城精选 对伴沙发</p>
									<p class="aui-slide-item-info">
										<span class="aui-slide-item-price">¥2399</span>&nbsp;&nbsp;<span class="aui-slide-item-mrk">¥9999</span>
									</p>
								</a>
							</li>
							<li class="aui-slide-item-item">
								<a href="ui-product.html" class="v-link">
									<img class="v-img" src="themes/img/pd/sf-23.jpg">
									<p class="aui-slide-item-title aui-slide-item-f-els">商城精选 韵白系列沙发三人位</p>
									<p class="aui-slide-item-info">
										<span class="aui-slide-item-price">¥9189</span>&nbsp;&nbsp;<span class="aui-slide-item-mrk">¥21299</span>
									</p>
								</a>
							</li>
							<li class="aui-slide-item-item">
								<a href="ui-product.html" class="v-link">
									<img class="v-img" src="themes/img/pd/sf-24.jpg">
									<p class="aui-slide-item-title aui-slide-item-f-els">商城精选 韵白系列沙发单人位</p>
									<p class="aui-slide-item-info">
										<span class="aui-slide-item-price">¥2349</span>&nbsp;&nbsp;<span class="aui-slide-item-mrk">¥4199</span>
									</p>
								</a>
							</li>
						</ul>
					</div>

				</div>
			</div>
		</div>
		<div class="aui-recommend">
			<img src="themes/img/bg/icon-tj1.jpg" alt="">
		</div>
		<section class="aui-list-product">
			<div class="aui-list-product-box" id = "recommend">
				<!-- <a href="ui-product.html" class="aui-list-product-item">
					<div class="aui-list-product-item-img">
						<img src="themes/img/pd/sf-15.jpg" alt="">
					</div>
					<div class="aui-list-product-item-text">
						<h3>KOBE LETTUCE 秋冬新款 女士日系甜美纯色半高领宽松套头毛衣针织衫</h3>
						<div class="aui-list-product-mes-box">
							<div>
							<span class="aui-list-product-item-price">
								<em>¥</em>
								399.99
							</span>
								<span class="aui-list-product-item-del-price">
								¥495.65
							</span>
							</div>
						</div>
					</div>
				</a>
				<a href="ui-product.html" class="aui-list-product-item">
					<div class="aui-list-product-item-img">
						<img src="themes/img/pd/sf-14.jpg" alt="">
					</div>
					<div class="aui-list-product-item-text">
						<h3>KOBE LETTUCE 秋冬新款 女士日系甜美纯色半高领宽松套头毛衣针织衫</h3>
						<div class="aui-list-product-mes-box">
							<div>
							<span class="aui-list-product-item-price">
								<em>¥</em>
								399.99
							</span>
								<span class="aui-list-product-item-del-price">
								¥495.65
							</span>
							</div>
						</div>
					</div>
				</a> -->
			</div>
		</section>
	</div>

	<footer class="aui-footer-default aui-footer-fixed">
		<a href="index.html" class="aui-footer-item aui-footer-active">
			<span class="aui-footer-item-icon aui-icon aui-footer-icon-home"></span>
			<span class="aui-footer-item-text">首页</span>
		</a>
		<a href="class.phtml" class="aui-footer-item">
			<span class="aui-footer-item-icon aui-icon aui-footer-icon-class"></span>
			<span class="aui-footer-item-text">分类</span>
		</a>
<!-- 		<a href="find.html" class="aui-footer-item">
			<span class="aui-footer-item-icon aui-icon aui-footer-icon-find"></span>
			<span class="aui-footer-item-text">发现</span>
		</a> -->
		<a href="car.html" class="aui-footer-item">
			<span class="aui-footer-item-icon aui-icon aui-footer-icon-car"></span>
			<span class="aui-footer-item-text">购物车</span>
		</a>
		<a href="ui-me.html" class="aui-footer-item">
			<span class="aui-footer-item-icon aui-icon aui-footer-icon-me"></span>
			<span class="aui-footer-item-text">我的</span>
		</a>
	</footer>
	<script type="text/javascript" src="themes/js/jquery.min.js"></script>
	<script type="text/javascript" src="themes/js/aui.js"></script>
</body>
<script type="text/javascript">
	$(function(){
		// 请求全部分类
		$.get('http://bdbbuy.com/mobile/categoryTree.php', function(data){
			var res = eval("(" + data + ")");
			level1 = res['children'][0]['children'];
			// console.log(level1);
			for(var i = 0; i < level1.length; i ++){
				level1_item = level1[i];
				// console.log(level1_item['name']);
				// 插入html
				id = level1_item['category_id'];
				if(id == 256 || id == 64 || id == 92 || id == 141 || id == 79 || id == 128 || id == 135 || id == 113 || id == 122 || id ==163){
					var str = '<a href="my-sign.html" class="aui-grid-row-item"><i class="aui-icon-large aui-icon-' + id + '"></i><p class="aui-grid-row-label">' + level1_item['name'] + '</p></a>';
					// $('div#category').append(str);
				}

			}
		});
		// 请求全部产品
		$.get('http://bdbbuy.com/mobile/productList.php', function(data){
			var res = eval("(" + data + ")");
			// console.log(res);
			for(var i = 0; i < res.length; i ++){
				product_item = res[i];
				product_id = product_item['product_id'];
				// if(product_id == 5006){
				if(product_item['sku'] == '2017111501' || product_item['sku'] == '2017111507' || product_item['sku'] == '2017111509' || product_item['sku'] == '20171115291' || product_item['sku'] == '2017111515' || product_item['sku'] == '2017111519'){
					// console.log(product_id);
					// var str = '<a href="ui-product.html" class="aui-list-product-item"><div class="aui-list-product-item-img"><img src="themes/img/pd/sf-14.jpg" alt=""></div><div class="aui-list-product-item-text"><h3>' + product_item['name'] + '</h3><div class="aui-list-product-mes-box"><div><span class="aui-list-product-item-price"><em>¥</em>399.99</span><span class="aui-list-product-item-del-price">¥495.65</span></div></div></div></a>';
					// $("#recommend").append(str);

				}
			}
		});
		// 请求生鲜水果商品信息
		fruit_lists = ['5919', '5925', '5929', '5951', '5911', '5917'];
		ids = fruit_lists.join('-');
		$.get('http://bdbbuy.com/mobile/productInfo.php?ids=' + ids, function(data){
			var results = eval("(" + data + ")");
			for(var i = 0; i < results.length; i ++){
				var res = results[i];
				var id = res['product_id'];
				// 请求商品图片
				$.ajax({
					type: 'get',
					url: 'http://bdbbuy.com/mobile/productImage.php?id=' + id,
					async: false,
					success: function(media){
						// console.log(res);
						var name = res['name'];
						var price = res['price'];
						var special_price = res['special_price'];
						var media = eval("(" + media + ")");
						var url = media[0]['url'];
						var str = '<li class="aui-slide-item-item"><a href="ui-product.html" class="v-link"><img class="v-img" src=' + url + '><p class="aui-slide-item-title aui-slide-item-f-els">' + name + '</p><p class="aui-slide-item-info"><span class="aui-slide-item-price">&nbsp;<em>CA$</em>' + price.substr(0,price.indexOf(".")+3) + '</span></p></a></li>';
						//&nbsp;&nbsp;<span class="aui-slide-item-mrk">' + price + '</span>
						$("#fruit").append(str);
					}
				});
			}
		});
		// 请求休闲零食信息
		
		// 请求坚果蜜饯
		// 请求个人护理

		// 请求精选推荐商品信息
		recommend_lists = ['5686', '5689', '5692', '5790', '5826', '5838', '5856', '5862', '5880', '5884', '5886', '5892'];
		ids = recommend_lists.join('-');
		$.get('http://bdbbuy.com/mobile/productInfo.php?ids=' + ids, function(data){
			var results = eval("(" + data + ")");
			// console.log(results);
			for(var i = 0; i < results.length; i ++){
				var res = results[i];
				var id = res['product_id'];
				// 请求商品图片
				$.ajax({
					type: 'get',
					url: 'http://bdbbuy.com/mobile/productImage.php?id=' + id,
					async: false,
					success: function(media){
						// console.log(res);
						var name = res['name'];
						var price = res['price'];
						var special_price = res['special_price'];
						var media = eval("(" + media + ")");
						var url = media[0]['url'];
						// console.log(url);
						var str = '<a href="ui-product.html" class="aui-list-product-item"><div class="aui-list-product-item-img"><img src="' + url + '" alt=""></div><div class="aui-list-product-item-text"><h3>' + name + '</h3><div class="aui-list-product-mes-box"><div><span class="aui-list-product-item-price"><em>CA$</em>' + price.substr(0,price.indexOf(".")+3) + '</span></div></div></div></a>';
						//<span class="aui-list-product-item-del-price"><em>$</em>' + special_price + '</span>
						$("#recommend").append(str);
					}
				});
			}
		});

	});
</script>
</html>