<!DOCTYPE html>
<html>
<?php
include('./config.php');
include('./user.php');
include('./address.php');
$type = $_GET['type'];
$userId = userid();
$addressList = array();
if ($userId != null) {
	$addressList = customer_address($userId);
}

?>

<head>
	<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no, minimal-ui"/>
	<meta name="apple-mobile-web-app-capable" content="yes"/>
	<meta name="apple-mobile-web-app-status-bar-style" content="black"/>
	<meta name="format-detection" content="telephone=no, email=no"/>
	<meta charset="UTF-8">
	<title><?php if ($type == 0) {
		echo '收货地址';
	}else{
		echo '账单地址';
	} ?></title>
	<link rel="stylesheet" href="themes/css/core.css">
	<link rel="stylesheet" href="themes/css/icon.css">
	<link rel="stylesheet" href="themes/css/home.css">
	<link rel="icon" type="image/x-icon" href="favicon.ico">
	<link href="iTunesArtwork@2x.png" sizes="114x114" rel="apple-touch-icon-precomposed">

</head>


<body style="background:#eee">

	<header class="aui-header-default aui-header-fixed aui-header-bg">
		<a href="javascript:history.back(-1)" class="aui-header-item">
			<i class="aui-icon aui-icon-back-white"></i>
		</a>
		<div class="aui-header-center aui-header-center-clear">
			<div class="aui-header-center-logo">
				<div class="aui-car-white-Typeface"><?php if ($type == 0) {
					echo '收货地址';
				}else{
					echo '账单地址';
				} ?></div>
			</div>
		</div>
		<a href="#" class="aui-header-item-icon"   style="min-width:0">
			<!--<i class="aui-icon aui-icon-search"></i>-->
		</a>
	</header>

	<section class="aui-myOrder-content">
		<?php foreach ($addressList as $add) {
		?>
		<div class="aui-Address-box" onclick="selectAddress('<?php echo $add['customer_address_id'] ?>')">
			<div class="aui-Address-box-item">
				<div class="aui-Address-box-item-bd">
					<p><?php echo $add['lastname'].$add['firstname']; ?></p>
				</div>
				<div class="aui-Address-box-item-ft">
					<p><?php echo $add['telephone']; ?></p>
				</div>
			</div>
			<div class="aui-Address-box-item">
				<div class="aui-Address-box-item-bd">
					<p><?php echo $add['street'].'  '.$add['city'].'  '.$add['country_id']; ?></p>
				</div>
			</div>
			<div class="aui-Address-box-item">
				<div class="aui-Address-box-item-bd">
					<?php
						if ($add['is_default_billing'] == true && $add['is_default_shipping'] == true) {
							echo '<p style="color:#999999">当前收货、账单地址</p>';
						}else if ($add['is_default_billing'] == true) {
							echo '<p style="color:#999999">当前账单地址</p>';
						}else if ($add['is_default_shipping'] == true) {
							echo '<p style="color:#999999">当前收货地址</p>';
						}
					 ?>
					<!-- <p><input type="checkbox" class="check goods-check goodsCheck" checked="checked" style="background-size: 17px 17px;"> <em style="padding-left:24px;">默认地址</em></p> -->
				</div>
				<div class="aui-Address-box-item-ft">
					<p onclick="deleteAddress('<?php echo $add['customer_address_id'] ?>')">删除</p>
				</div>
			</div>
		</div>
		<?php } ?>
		<div class="aui-out">
			<a href="my-edit-address.phtml?type=<?php echo $type; ?>">新建<?php if ($type == 0) {
				echo '收货地址';
			}else{
				echo '账单地址';
			} ?></a>
		</div>
	</section>

	<script type="text/javascript" src="themes/js/jquery.min.js"></script>
	<script type="text/javascript" src="themes/js/aui.js"></script>
	<script type="text/javascript" >
		function deleteAddress(address_id){
			event.cancelBubble=true;
		    var r=confirm("删除该地址？")
			    if (r==true) {
					
					$.ajax({  

				        url:"<?php echo $baseHost; ?>address.php",           

				        type: "POST",

				        data:{delete_address:1,address_id:address_id},         

				        success:function(result){  
				        	if (result == "") {
				        		window.location.href="<?php echo $baseHost; ?>my-addres.phtml?type=<?php echo $type; ?>";
				        	}else{
				        		alert("删除失败");
				        	}
				        },

				        error:function(XMLHttpRequest, textStatus, errorThrown){

				        }

				    });
			}

		}
		function selectAddress(address_id){
			$.ajax({  

		        url:"<?php echo $baseHost; ?>address.php",           

		        type: "POST",

		        data:{update:<?php echo $type; ?>,address_id:address_id},         

		        success:function(result){  
		        	if (result == "") {
		        		window.location.href="?php echo $baseHost; ?>order-sure.phtml";
		        	}else{
		        		alert("选择失败，请重试");
		        	}
		        },

		        error:function(XMLHttpRequest, textStatus, errorThrown){

		            

		        }

		    });
		}
        /**
         * Javascript API调用Tab
         */
        !function ($) {
            var $tab = $('#J_Tab');

            $tab.tab({
                nav: '.tab-nav-item',
                panel: '.tab-panel-item',
                activeClass: 'tab-active'
            });

			/*
			 $tab.find('.tab-nav-item').on('open.ydui.tab', function (e) {
			 console.log('索引：%s - [%s]正在打开', e.index, $(this).text());
			 });
			 */

            $tab.find('.tab-nav-item').on('opened.ydui.tab', function (e) {
                console.log('索引：%s - [%s]已经打开了', e.index, $(this).text());
            });
        }(jQuery);
	</script>

</body>
</html>