<!DOCTYPE html>
<html>
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no, minimal-ui"/>
	<meta name="apple-mobile-web-app-capable" content="yes"/>
	<meta name="apple-mobile-web-app-status-bar-style" content="black"/>
	<meta name="format-detection" content="telephone=no, email=no"/>
	<meta charset="UTF-8">
	<title>收货地址</title>
	<link rel="stylesheet" href="themes/css/core.css">
	<link rel="stylesheet" href="themes/css/icon.css">
	<link rel="stylesheet" href="themes/css/home.css">
	<link rel="icon" type="image/x-icon" href="favicon.ico">
	<link href="iTunesArtwork@2x.png" sizes="114x114" rel="apple-touch-icon-precomposed">
	<style>
		.m-cell {
			background-color: #FFF;
			position: relative;
			z-index: 1;
			margin-bottom: .35rem;
			height: 3rem;
			line-height: 3rem;
		}
	</style>

</head>
<script>
function save(){
	var shipping_lastname = $('#shipping-lastname').val();
	var shipping_firstname = $('#shipping-firstname').val();
	var shipping_phone = $('#shipping-phone').val();
	var shipping_postcode = $('#shipping-postcode').val();
	var shipping_area = $('#shipping-area').val();
	var shipping_street = $('#shipping-street').val();
	var useShippingAddress = $('#useShippingAddress').checked();
	var billing_lastname = $('#billing-lastname').val();
	var billing_firstname = $('#billing-firstname').val();
	var billing_phone = $('#billing-phone').val();
	var billing_postcode = $('#billing-postcode').val();
	var billing_area = $('#billing-area').val();
	var billing_street = $('#billing-street').val();
	$.ajax({  

        url:"http://bdbbuy.com/mobile/address.php",           

        type: "POST",

        data:{slastname:shipping_lastname,sfirstname:shipping_firstname,sphone:shipping_phone,spostcode:shipping_postcode,sarea:shipping_area,sstreet:shipping_street,blastname:billing_lastname,bfirstname:billing_firstname,bphone:billing_phone,bpostcode:billing_postcode,barea:billing_area,bstreet:billing_street},         

        success:function(result){  

        	var res = eval("(" + result + ")");
            if (res['status'] == 'OK') {
            	window.location.href='http://bdbbuy.com/mobile/ui-me.phtml';
            	document.cookie="bdb-ui="+res['userData']['customer_id'];
            }else
            {
            	document.location.reload();
            }
        },

        error:function(XMLHttpRequest, textStatus, errorThrown){

            

        }

    });
}
</script>
<body style="background:#eee">

	<header class="aui-header-default aui-header-fixed aui-header-bg">
		<a href="javascript:history.back(-1)" class="aui-header-item">
			<i class="aui-icon aui-icon-back-white"></i>
		</a>
		<div class="aui-header-center aui-header-center-clear">
			<div class="aui-header-center-logo">
				<div class="aui-car-white-Typeface">收货地址</div>
			</div>
		</div>
		<a href="#" class="aui-header-item-icon"   style="min-width:0">
			<!--<i class="aui-icon aui-icon-search"></i>-->
		</a>
	</header>


	<section class="aui-myOrder-content">
		<div class="aui-prompt"><i class="aui-icon aui-prompt-sm"></i>填写您的收货信息</div>
		<div class="aui-Address-box shipping">
			<p>
				<span id="shipping-lastname" class="aui-Address-box-head">名</span><input class="aui-Address-box-input" type="text" placeholder="名">
			</p>
			<p>
				<span id="shipping-firstname" class="aui-Address-box-head">姓</span><input class="aui-Address-box-input" type="text" placeholder="姓">
			</p>
			<p>
				<span id="shipping-phone" class="aui-Address-box-head">手机号</span><input class="aui-Address-box-input" type="text" placeholder="手机号码">
			</p>
			<p>
				<span id="shipping-postcode" class="aui-Address-box-head">邮编</span><input class="aui-Address-box-input" type="text" placeholder="邮编">
			</p>
			<p>
				<!-- <span class="aui-Address-box-head">地区</span><input class="aui-Address-box-input" type="text" readonly id="J_Address"  placeholder="所在地区"> -->
				<span id="shipping-area" class="aui-Address-box-head">地区</span><input class="aui-Address-box-input" type="text" value="安大略，加拿大" disabled="disabled">
			</p>
			<p>
				<textarea  id="shipping-street" class="aui-Address-box-text" placeholder="街道， 小区门牌等详细地址" rows="3"></textarea>
			</p>

		</div>
		<div class="aui-out">
			<a onclick="save()" class="red-color" style="color:#fff">保存并使用</a>
		</div>
	</section>


	<script type="text/javascript" src="themes/js/jquery.min.js"></script>
	<script type="text/javascript" src="themes/js/aui.js"></script>
	<script type="text/javascript" src="themes/js/city.js"></script>
	<script type="text/javascript" >
        /**
         * Javascript API调用Tab
         */
        !function ($) {
            var $tab = $('#J_Tab');

            $tab.tab({
                nav: '.tab-nav-item',
                panel: '.tab-panel-item',
                activeClass: 'tab-active'
            });

			/*
			 $tab.find('.tab-nav-item').on('open.ydui.tab', function (e) {
			 console.log('索引：%s - [%s]正在打开', e.index, $(this).text());
			 });
			 */

            $tab.find('.tab-nav-item').on('opened.ydui.tab', function (e) {
                console.log('索引：%s - [%s]已经打开了', e.index, $(this).text());
            });
        }(jQuery);
	</script>
	<script>
        /**
         * 默认调用
         */
        !function () {
            var $target = $('#J_Address');

            $target.citySelect();

            $target.on('click', function (event) {
                event.stopPropagation();
                $target.citySelect('open');
            });

            $target.on('done.ydui.cityselect', function (ret) {
                $(this).val(ret.provance + ' ' + ret.city + ' ' + ret.area);
            });
        }();
        /**
         * 设置默认值
         */
        !function () {
            var $target = $('#J_Address2');

            $target.citySelect({
                provance: '新疆',
                city: '乌鲁木齐市',
                area: '天山区'
            });

            $target.on('click', function (event) {
                event.stopPropagation();
                $target.citySelect('open');
            });

            $target.on('done.ydui.cityselect', function (ret) {
                $(this).val(ret.provance + ' ' + ret.city + ' ' + ret.area);
            });
        }();
	</script>

</body>
</html>