<!DOCTYPE html>
<html>
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no, minimal-ui"/>
	<meta name="apple-mobile-web-app-capable" content="yes"/>
	<meta name="apple-mobile-web-app-status-bar-style" content="black"/>
	<meta name="format-detection" content="telephone=no, email=no"/>
	<meta charset="UTF-8">
	<title>设置</title>
	<link rel="stylesheet" href="themes/css/core.css">
	<link rel="stylesheet" href="themes/css/icon.css">
	<link rel="stylesheet" href="themes/css/home.css">
	<link rel="icon" type="image/x-icon" href="favicon.ico">
	<link href="iTunesArtwork@2x.png" sizes="114x114" rel="apple-touch-icon-precomposed">

	<!-- jquerWeui -->
	<link href="https://cdn.bootcss.com/weui/1.1.2/style/weui.min.css" rel="stylesheet">
	<link href="res/css/jq-1-2-0-weui.css" rel="stylesheet">
	
</head>
<?php
	include('./config.php');
?>
<body style="background:#f0f0f0">

	<header class="aui-header-default aui-header-fixed aui-header-bg">
		<a href="javascript:history.back(-1)" class="aui-header-item">
			<i class="aui-icon aui-icon-back-white"></i>
		</a>
		<div class="aui-header-center aui-header-center-clear">
			<div class="aui-header-center-logo">
				<div class="aui-car-white-Typeface">设置</div>
			</div>
		</div>
		<a href="#" class="aui-header-item-icon"   style="min-width:0">
			<i class="aui-icon aui-icon-share-pd"></i>
		</a>
	</header>

	<section class="aui-myOrder-content">
		<div class="aui-product-set">

			<!-- <a href="#" class="aui-address-cell aui-fl-arrow aui-fl-arrow-clear" data-ydui-actionsheet="{target:'#actionSheet',closeElement:'#cancel'}">
				<div class="aui-address-cell-bd">个人信息</div>
				<div class="aui-address-cell-ft"></div>
			</a>
			<a href="my-address.html" class="aui-address-cell aui-fl-arrow aui-fl-arrow-clear" data-ydui-actionsheet="{target:'#actionSheet',closeElement:'#cancel'}">
				<div class="aui-address-cell-bd">我的实名认证</div>
				<div class="aui-address-cell-ft"></div>
			</a> -->
			<a href="my-address.phtml" class="aui-address-cell aui-fl-arrow aui-fl-arrow-clear" data-ydui-actionsheet="{target:'#actionSheet',closeElement:'#cancel'}">
				<div class="aui-address-cell-bd">我的收货地址</div>
				<div class="aui-address-cell-ft"></div>
			</a>

			<a href="#" onclick="alertSet()" class="aui-address-cell aui-fl-arrow aui-fl-arrow-clear">
				<div class="aui-address-cell-bd">重置密码</div>
				<div class="aui-address-cell-ft"></div>
			</a>

			<!-- <a href="getPassword.phtml?tip=重置密码" class="aui-address-cell aui-fl-arrow aui-fl-arrow-clear">
				<div class="aui-address-cell-bd">重置密码</div>
				<div class="aui-address-cell-ft"></div>
			</a> -->

			
			<!-- <a href="#" class="aui-address-cell aui-fl-arrow aui-fl-arrow-clear" data-ydui-actionsheet="{target:'#actionSheet',closeElement:'#cancel'}">
				<div class="aui-address-cell-bd">消息推送设置</div>
				<div class="aui-address-cell-ft"></div>
			</a>
			<a href="#" class="aui-address-cell aui-fl-arrow aui-fl-arrow-clear" data-ydui-actionsheet="{target:'#actionSheet',closeElement:'#cancel'}">
				<div class="aui-address-cell-bd">清除缓存</div>
				<div class="aui-address-cell-ft"></div>
			</a>
			<a href="#" class="aui-address-cell aui-fl-arrow aui-fl-arrow-clear" data-ydui-actionsheet="{target:'#actionSheet',closeElement:'#cancel'}">
				<div class="aui-address-cell-bd">弹幕设置</div>
				<div class="aui-address-cell-ft"></div>
			</a>
			<div class="aui-dri"></div>
			<a href="#" class="aui-address-cell aui-fl-arrow aui-fl-arrow-clear" data-ydui-actionsheet="{target:'#actionSheet',closeElement:'#cancel'}">
				<div class="aui-address-cell-bd">关于我们</div>
				<div class="aui-address-cell-ft">v5.0</div>
			</a> -->
		</div>
		<?php
		include_once('./user.php');
		if (islogin()) {
			echo '<div class="aui-out">';
			echo '<a class="red-color" style="color:#fff" onclick="logout()">退出当前账号</a>';
			echo '</div>';
		}else
		{
			echo '<script type="text/javascript">';
			echo 'window.location.href="' . $baseHost . 'index.phtml";';
			echo '</script>';
		}
		?>
	</section>


	<script type="text/javascript" src="res/js/config.js"></script>
	<script type="text/javascript" src="themes/js/jquery.min.js"></script>
	<script type="text/javascript" src="themes/js/aui.js"></script>
	<script type="text/javascript" src="res/js/my-set.js"></script>

	<!-- jqweui -->
	<script type="text/javascript" src="themes/js/jquery.min.js"></script>
	<script src="https://cdn.bootcss.com/jquery-weui/1.2.0/js/jquery-weui.min.js"></script>
</body>
</html>