<!DOCTYPE html>
<html>
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no, minimal-ui"/>
	<meta name="apple-mobile-web-app-capable" content="yes"/>
	<meta name="apple-mobile-web-app-status-bar-style" content="black"/>
	<meta name="format-detection" content="telephone=no, email=no"/>
	<meta charset="UTF-8">
	<title>游客信息</title>
	<link rel="stylesheet" href="themes/css/core.css">
	<link rel="stylesheet" href="themes/css/icon.css">
	<link rel="stylesheet" href="themes/css/home.css">
	<link rel="icon" type="image/x-icon" href="favicon.ico">
	<script src="themes/js/jquery.min.js"></script>
	<link href="iTunesArtwork@2x.png" sizes="114x114" rel="apple-touch-icon-precomposed">
</head>
<?php

$shipping=null;
$billing=null;
if (isset($_COOKIE['bdb-shipping'])) {
	$shipping = json_decode($_COOKIE['bdb-shipping'],true);
}

if (isset($_COOKIE['bdb-billing'])) {
	$billing = json_decode($_COOKIE['bdb-billing'],true);
}

?>
<body>
	<header class="aui-header-default aui-header-fixed aui-header-bg">
		<a href="javascript:history.back(-1)" class="aui-header-item">
			<i class="aui-icon aui-icon-back-white"></i>
		</a>
		<div class="aui-header-center aui-header-center-clear">
			<div class="aui-header-center-logo">
				<div class="aui-car-white-Typeface">游客信息</div>
			</div>
		</div>
		<a href="login.html" class="aui-header-item-icon"   style="color: #fff;font-size: 16px;">
			<!-- <i class="aui-icon aui-icon-member"></i> -->
			登录
		</a>
	</header>

		<div>

			<section class="aui-myOrder-content">
				<div class="aui-prompt"><i class="aui-icon aui-prompt-sm"></i>填写您的地址信息</div>
				<div class="aui-Address-box shipping">
					<p>
						<span class="aui-Address-box-head">名</span><input id="shipping-lastname" class="aui-Address-box-input" type="text" placeholder="名" value="<?php echo json_decode('"'.str_replace('%', '\\', $shipping['lastname']).'"'); ?>">
					</p>
					<p>
						<span class="aui-Address-box-head">姓</span><input id="shipping-firstname" class="aui-Address-box-input" type="text" placeholder="姓" value="<?php echo json_decode('"'.str_replace('%', '\\', $shipping['firstname']).'"'); ?>">
					</p>
					<p>
						<span class="aui-Address-box-head">手机号</span><input id="shipping-phone" class="aui-Address-box-input" type="text" placeholder="手机号码" value="<?php echo json_decode('"'.str_replace('%', '\\', $shipping['phone']).'"'); ?>">
					</p>

<!-- 					<p>
						<span class="aui-Address-box-head">邮箱</span><input id="shipping-email" class="aui-Address-box-input" type="text" placeholder="邮箱" value="<?php //echo json_decode('"'.str_replace('%', '\\', $shipping['email']).'"'); ?>">
					</p> -->

					<p>
						<span class="aui-Address-box-head">邮编</span><input id="shipping-postcode" class="aui-Address-box-input" type="text" placeholder="邮编" value="<?php echo json_decode('"'.str_replace('%', '\\', $shipping['postcode']).'"'); ?>">
					</p>
					<p>
						<span class="aui-Address-box-head">地区</span><input id="shipping-area" class="aui-Address-box-input" type="text" value="安大略，加拿大" disabled="disabled">
					</p>
					<p>
						<textarea  id="shipping-street" class="aui-Address-box-text" placeholder="街道， 小区门牌等详细地址" rows="3" ><?php echo json_decode('"'.str_replace('%', '\\', $shipping['street']).'"'); ?></textarea>
					</p>

				</div>
			</section>

			<section class="aui-myOrder-content">
				<div class="aui-prompt"><i class="aui-icon aui-prompt-sm"></i>填写您的账单信息(不填写默认使用收货地址)</div>
				<div class="aui-Address-box shipping">
					<p>
						<span class="aui-Address-box-head">名</span><input id="billing-lastname" class="aui-Address-box-input" type="text" placeholder="名"  value="<?php echo json_decode('"'.str_replace('%', '\\', $billing['lastname']).'"'); ?>">
					</p>
					<p>
						<span class="aui-Address-box-head">姓</span><input id="billing-firstname" class="aui-Address-box-input" type="text" placeholder="姓"  value="<?php echo json_decode('"'.str_replace('%', '\\', $billing['firstname']).'"'); ?>">
					</p>
					<p>
						<span class="aui-Address-box-head">手机号</span><input id="billing-phone" class="aui-Address-box-input" type="text" placeholder="手机号码"   value="<?php echo json_decode('"'.str_replace('%', '\\', $billing['phone']).'"'); ?>">
					</p>
					<p>
						<span class="aui-Address-box-head">邮编</span><input id="billing-postcode" class="aui-Address-box-input" type="text" placeholder="邮编"   value="<?php echo json_decode('"'.str_replace('%', '\\', $billing['postcode']).'"'); ?>">
					</p>
					<p>
						<span class="aui-Address-box-head">地区</span><input id="billing-area" class="aui-Address-box-input" type="text"   value="<?php echo json_decode('"'.str_replace('%', '\\', $billing['area']).'"'); ?>">
					</p>
					<p>
						<textarea  id="billing-street" class="aui-Address-box-text" placeholder="街道， 小区门牌等详细地址" rows="3" ><?php echo json_decode('"'.str_replace('%', '\\', $billing['street']).'"'); ?></textarea>
					</p>

				</div>
			</section>
			<br>
			<br>
			<br>

			<div class="aui-payment-bar">
				<div class="shop-total">

				</div>
				<a class="settlement" onclick="ordersure_nologin()">提交订单</a>
			</div>
		</div>
		


<script>
	function setCookie(c_name,value,expiredays)
	{
		var exdate=new Date()
		exdate.setDate(exdate.getDate()+expiredays)
		document.cookie=c_name+ "=" +escape(value)+
		((expiredays==null) ? "" : ";expires="+exdate.toGMTString())
	}

	function ordersure_nologin(){
		var shipping_lastname = $('#shipping-lastname').val();
		var shipping_firstname = $('#shipping-firstname').val();
		var shipping_phone = $('#shipping-phone').val();
		var shipping_email = 'bdbbuy@gmail.com';
		var shipping_postcode = $('#shipping-postcode').val();
		var shipping_area = $('#shipping-area').val();
		var shipping_street = $('#shipping-street').val();

		if (shipping_lastname == "" || shipping_firstname=="" || shipping_phone=="" || shipping_postcode=="" || shipping_area=="" || shipping_street=="") {
			alert('收货地址每一项都是必填项');
			return;
		};

		var billing_lastname = $('#billing-lastname').val();
		var billing_firstname = $('#billing-firstname').val();
		var billing_phone = $('#billing-phone').val();
		var billing_postcode = $('#billing-postcode').val();
		var billing_area = $('#billing-area').val();
		var billing_street = $('#billing-street').val();

		if (billing_lastname=="") {
			billing_lastname = shipping_lastname;
		};
		if (billing_firstname=="") {
			billing_firstname = shipping_firstname;
		};
		if (billing_phone=="") {
			billing_phone = shipping_phone;
		};
		if (billing_postcode=="") {
			billing_postcode = shipping_postcode;
		};
		if (billing_area=="") {
			billing_area = shipping_area;
		};
		if (billing_street=="") {
			billing_street = shipping_street;
		};


		var shipping = {};
		shipping.lastname = shipping_lastname;
		shipping.firstname = shipping_firstname;
		shipping.phone    = shipping_phone;
		shipping.email = shipping_email;
		shipping.postcode = shipping_postcode;
		shipping.area     = shipping_area;
		shipping.street   = shipping_street;

		var billing = {};
		billing.lastname = billing_lastname;
		billing.firstname= billing_firstname;
		billing.phone    = billing_phone;
		billing.postcode = billing_postcode;
		billing.area     = billing_area;
		billing.street   = billing_street;



		var shipping_json = JSON.stringify(shipping);
		setCookie("bdb-shipping", shipping_json);

		var billing_json = JSON.stringify(billing);
		setCookie("bdb-billing", billing_json);

		window.location.href='http://bdbbuy.com/mobile/order-sure.phtml';



	}


</script>

</body>
</html>