<!DOCTYPE html>
<html>
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no, minimal-ui"/>
	<meta name="apple-mobile-web-app-capable" content="yes"/>
	<meta name="apple-mobile-web-app-status-bar-style" content="black"/>
	<meta name="format-detection" content="telephone=no, email=no"/>
	<meta charset="UTF-8">
	<title>下单</title>
	<link rel="stylesheet" href="themes/css/core.css">
	<link rel="stylesheet" href="themes/css/icon.css">
	<link rel="stylesheet" href="themes/css/home.css">
	<script type="text/javascript" src="themes/js/jquery.min.js"></script>
	<link rel="icon" type="image/x-icon" href="favicon.ico">
	<link href="iTunesArtwork@2x.png" sizes="114x114" rel="apple-touch-icon-precomposed">
</head>
<?php
ini_set('display_errors',1); 
include('./user.php');
include_once('./cart.php');
include('./address.php');

#用户or游客
$userId = userid();
$isLogin = false;
if ($userId != null) {
	$isLogin = true;
}

#用户
#需要设置个人、地址、账单信息。
#信息完整才能展示价格等数据。
if ($isLogin) {
	$userinfo = userinfo();
	
	$addressList = array();
	$shippingAddress = null;
	$billingAddress = null;
	if ($userId != null) {
		$addressList = customer_address($userId);
		foreach ($addressList as $item) {
			if ($item['is_default_billing']) {
				$billingAddress = $item;
			}
			if ($item['is_default_shipping']) {
				$shippingAddress = $item;
			}
		}
	}
	$userinfo['phone'] = $shippingAddress['telephone'];
	if ($shippingAddress == null || $billingAddress == null) {
		echo '<script>url="http://bdbbuy.com/mobile/my-edit-address.phtml";window.location.href=url;</script> ';
	}
}else{
	#未登录&&没有缓存的配送信息
	$shipping=null;
	$billing=null;
	if (isset($_COOKIE['bdb-shipping'])) {
		$shipping = json_decode($_COOKIE['bdb-shipping'],true);
	}

	if (isset($_COOKIE['bdb-billing'])) {
		$billing = json_decode($_COOKIE['bdb-billing'],true);
	}
	if ($shipping == null || $billing == null) {
		echo '<script>url="http://bdbbuy.com/mobile/order.phtml";window.location.href=url;</script> ';
	}else{
		var_dump(json_decode('"'.str_replace('%', '\\', $shipping['email'])));
		$userinfo = array(
				'email' => json_decode('"'.str_replace('%', '\\', $shipping['email']).'"'),
				'firstname' => json_decode('"'.str_replace('%', '\\', $shipping['firstname']).'"'),
				'lastname' => json_decode('"'.str_replace('%', '\\', $shipping['lastname']).'"'),
				'phone' => json_decode('"'.str_replace('%', '\\', $shipping['phone']).'"')

			);
		$shippingAddress = array(
				'firstname' => json_decode('"'.str_replace('%', '\\', $shipping['firstname']).'"'),
				'lastname' => json_decode('"'.str_replace('%', '\\', $shipping['lastname']).'"'),
				'telephone' => json_decode('"'.str_replace('%', '\\', $shipping['phone']).'"'),
				'street' => json_decode('"'.str_replace('%', '\\', $shipping['street']).'"'),
				'city' => json_decode('"'.str_replace('%', '\\', $shipping['area']).'"'),
				'postcode' => json_decode('"'.str_replace('%', '\\', $shipping['postcode']).'"'),
				'email' => json_decode('"'.str_replace('%', '\\', $shipping['email']).'"'),
				'country_id' => "CA"
			);
		$billingAddress = array(
				'firstname' => json_decode('"'.str_replace('%', '\\', $billing['firstname']).'"'),
				'lastname' => json_decode('"'.str_replace('%', '\\', $billing['lastname']).'"'),
				'telephone' => json_decode('"'.str_replace('%', '\\', $billing['phone']).'"'),
				'street' => json_decode('"'.str_replace('%', '\\', $billing['street']).'"'),
				'city' => json_decode('"'.str_replace('%', '\\', $billing['area']).'"'),
				'postcode' => json_decode('"'.str_replace('%', '\\', $billing['postcode']).'"'),
				'country_id' => "CA"
			);
	}
}

#开始下单
include('./order.php');
$cartid = cartid();
$userinfo_complete = false;
$address_complete = false;
$payment_complete = false;
#设置用户信息
if ($isLogin) {
	$userinfo_complete = set_cart_user($cartid,$userinfo,"customer");
}else{
	$userinfo_complete = set_cart_user($cartid,$userinfo,"guest");
}
#设置购物车地址信息
$address_complete = set_cart_address($cartid,$billingAddress,$shippingAddress);
#设置支付信息
$payment_complete = set_payment($cartid);
#设置配送方式
$shipping_complete = set_shipping($cartid);

#购物车信息

$carinfo = cart($cartid);
$carItems = $carinfo['items'];
$products = array();
foreach ($carItems as $item) {
	$product_id = $item['product_id'];
	$url='http://bdbbuy.com/mobile/productInfo.php?ids='.$product_id;
	$jsonResult = json_decode(file_get_contents($url),true);
	if (count($jsonResult) > 0) {
		$product = $jsonResult[0];
	}
	$product['qty'] = $item['qty'];
	$product['discount_price'] = $item['price'];
	array_push($products, $product);
}


?>
<body>
	<header class="aui-header-default aui-header-fixed aui-header-bg">
		<a href="javascript:history.back(-1)" class="aui-header-item">
			<i class="aui-icon aui-icon-back-white"></i>
		</a>
		<div class="aui-header-center aui-header-center-clear">
			<div class="aui-header-center-logo">
				<div class="aui-car-white-Typeface">填写订单</div>
			</div>
		</div>
		<a href="#" class="aui-header-item-icon"   style="min-width:0">
			<i class="aui-icon aui-icon-member"></i>
		</a>
	</header>
	<section class="aui-address-content">

		<div class="aui-address-box">
			<div class="aui-address-box-list">
				<a href="my-addres.phtml" class="aui-address-box-default">
					<ul>
						<li>
							<strong><?php echo $shippingAddress['firstname'].$shippingAddress['lastname'].'  '.$shippingAddress['telephone']; ?></strong>
							<span class="aui-tag" id="aui-home">收货地址</span>
							<span class="aui-tag aui-tag-default" id="aui-default">默认</span>
						</li>
						<li>
							<i class="aui-icon aui-icon-address"></i>
							<?php echo $shippingAddress['street'].'  '.$shippingAddress['city'].'  '.$shippingAddress['country_id']; ?>
						</li>
					</ul>
				</a>
			</div>
		</div>

		<div class="aui-address-box">
			<div class="aui-address-box-list">
				<a href="my-addres.phtml" class="aui-address-box-default">
					<ul>
						<li>
							<strong><?php echo $billingAddress['firstname'].$billingAddress['lastname'].'  '.$billingAddress['telephone']; ?></strong>
							<span class="aui-tag" id="aui-home">账单地址</span>
							<span class="aui-tag aui-tag-default" id="aui-default">默认</span>
						</li>
						<li>
							<i class="aui-icon aui-icon-address"></i>
							<?php echo $billingAddress['street'].'  '.$billingAddress['city'].'  '.$billingAddress['country_id']; ?>
						</li>
					</ul>
				</a>
			</div>
		</div>

		<div class="aui-dri"></div>
		<div class="aui-list-product-float-item">

					<?php
						foreach ($products as $product) {
							echo '<a href="javascript:;" class="aui-list-product-fl-item">';
							echo '<div class="aui-list-product-fl-img">';
							echo '<img src="http://bdbbuy.com/media/catalog/product'.$product['image'].'" alt="">';
							echo '</div>';
							echo '<div class="aui-list-product-fl-text">';
							echo '<h3 class="aui-list-product-fl-title">'.$product['name'].$product['short_description'].'</h3>';
							echo '<div class="aui-list-product-fl-mes">';
							echo '<div>';
							echo '<span class="aui-list-product-item-price">';
							echo '<em>CA$</em>';
							echo number_format($product['price'],2);
							echo '</span>';
							if ($product['discount_price'] != $product['price']) {
								echo '<span class="aui-list-product-item-del-price">';
								echo 'CA$'.$product['discount_price'];
								echo '</span>	';

							}

							echo '</div>';
							echo '<div class="aui-btn-purchase">';
							echo '<span>'.$product['qty'].'</span>';
							echo '</div>';
							echo '</div>';
							echo '</div>';
							echo '</a>';
						}
					 ?>

<!-- 					<div class="aui-list-product-fl-bag">
						<span><img src="themes/img/icon/bag1.png" alt=""></span>
						<span><img src="themes/img/icon/bag2.png" alt=""></span>
					</div> -->

		</div>
		<div class="aui-address-well">
			<a href="#" class="aui-address-cell aui-fl-arrow">
				<div class="aui-address-cell-bd">支持配送</div>
				<div class="aui-address-cell-ft">
					<p class="aui-address-text"><i class="aui-icon aui-prompt-sm"></i>次日15:00-22:00</p>
				</div>
			</a>
			<div class="aui-prompt"><i class="aui-icon aui-prompt-sm"></i>当天21点前下单，可享次日达~</div>

			<div class="aui-dri"></div>

			<div class="aui-dri"></div>
			<div>
				<a href="#" class="aui-address-cell aui-fl-arrow aui-fl-arrow-clear">
					<div class="aui-address-cell-bd">
						<h3>商品金额</h3>
						<p>税</p>
						<p>运费</p>
					</div>
					<div class="aui-address-cell-ft">
						<span class="aui-red">CA$<?php echo number_format($carinfo['subtotal'],2) ?></span><br>
						<span class="aui-red">+CA$<?php echo number_format($carinfo['shipping_address']['tax_amount'],2); ?></span><br>
						<span class="aui-red">+CA$<?php echo number_format($carinfo['shipping_address']['shipping_amount'],2); ?></span>
					</div>
				</a>
			</div>
		</div>
		<div class="aui-payment-bar">
			<div class="shop-total">
				<span class="aui-red aui-size">实付款: <em>CA$<?php echo number_format($carinfo['grand_total'],2) ?></em></span>
			</div>
			<?php echo '<a href="javascript:void(0);" class="settlement" onclick="gopay(\''.$cartid.'\')">去支付</a>'; ?>
		</div>
	</section>
<script type="text/javascript">

 function gopay(mCartId) { 
		$.ajax({  

            url:"http://bdbbuy.com/mobile/pptest.php",           

            type: "POST",

            data:{cartid:mCartId},         

            success:function(result){  

            	window.location.href=result;
            },

            error:function(XMLHttpRequest, textStatus, errorThrown){

                

            }

	    });

 }
 </script>
</body>
</html>