<!DOCTYPE html>
<html>
<?php
$msg = $_GET["msg"];
?>
<head>
	<title>支付异常</title>
	<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no, minimal-ui"/>
	<meta name="apple-mobile-web-app-capable" content="yes"/>
	<meta name="apple-mobile-web-app-status-bar-style" content="black"/>
	<meta name="format-detection" content="telephone=no, email=no"/>
	<meta charset="UTF-8">
	<link rel="icon" type="image/x-icon" href="favicon.ico">
	<link href="iTunesArtwork@2x.png" sizes="114x114" rel="apple-touch-icon-precomposed">
	<link rel="stylesheet" href="themes/css/core.css">
	<link rel="stylesheet" href="themes/css/icon.css">
	<link rel="stylesheet" href="themes/css/home.css">

	<!-- jquerWeui -->
	<link href="https://cdn.bootcss.com/weui/1.1.2/style/weui.min.css" rel="stylesheet">
	<link href="https://cdn.bootcss.com/jquery-weui/1.2.0/css/jquery-weui.min.css" rel="stylesheet">

	<style type="text/css">
		
		.kefu{
		    display: inline-block;
			vertical-align: middle;
		}
		.info{
			color:#8a8a8a;
		}
	</style>

</head>
<body>
	<header class="aui-header-default aui-header-fixed aui-header-bg">
		<a href="javascript:history.back(-1)" class="aui-header-item">
			<i class="aui-icon aui-icon-back-white"></i>
		</a>
		<div class="aui-header-center">
			<div class="aui-header-center-logo">
				<div class="aui-car-white-Typeface">支付异常</div>
			</div>
		</div>
		<a href="kefu.html" class="aui-header-item-icon"   style="color: #fff;font-size: 16px;padding-right: 0px;">
			<!-- <i class="aui-icon aui-icon-member"></i> -->
			客服
		</a>
	</header>

	<div class="weui-msg" style="margin-top: 80px;">
	  <div class="weui-msg__icon-area">
	  	<!-- <i class="weui-icon-success weui-icon_msg" style="color: #ed3e6e;"></i> -->
	  	<img class="kefu" src="res/icon/icon_payError.png">
	  </div>
	  <div class="weui-msg__text-area">
	    <h2 class="weui-msg__title info">错误信息：<?php echo $msg; ?></h2>
	  </div>
	  
	  <div class="weui-msg__extra-area">
	    <div class="weui-footer">
	      <p class="weui-footer__links">
	        <a href="javascript:void(0);" class="weui-footer__link">八点半买</a>
	      </p>
	      <p class="weui-footer__text">Copyright © 2008-2017 bdbbuy</p>
	    </div>
	  </div>
	</div>

	<script type="text/javascript" src="themes/js/jquery.min.js"></script>
	<script src="https://cdn.bootcss.com/jquery-weui/1.2.0/js/jquery-weui.min.js"></script>
</body>
</html>