<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0"/>
	<meta name="apple-mobile-web-app-capable" content="yes"/>
	<meta name="apple-mobile-web-app-status-bar-style" content="black"/>
	<meta name="format-detection" content="telephone=no, email=no"/>
	<meta charset="UTF-8">
	<title>搜索结果</title>
	<link rel="stylesheet" href="themes/css/core.css">
	<link rel="stylesheet" href="themes/css/icon.css">
	<link rel="stylesheet" href="themes/css/home.css">
	<link rel="stylesheet" href="themes/css/add.css">
	<link rel="stylesheet" href="themes/css/amazeui.min.css">
	<link rel="icon" type="image/x-icon" href="favicon.ico">
	<link href="iTunesArtwork@2x.png" sizes="114x114" rel="apple-touch-icon-precomposed">
</head>
<?php 
$keyword=$_GET['s'];
$url='http://bdbbuy.com/mobile/searchProduct.php?s='.$keyword;
$products = json_decode(file_get_contents($url),true);
?>



<body style="padding-left:10px;padding-right:10px">
	<header class="aui-header-default aui-header-fixed aui-header-bg">
		<a href="#" class="aui-header-item"  style="display:none">
			<i class="aui-icon aui-icon-code"></i>
		</a>
		<div class="aui-header-center aui-header-center-clear">
			<div class="aui-header-search-box">
				<i class="aui-icon aui-icon-small-search"></i>
				<form action="searchProduct.phtml" method="get">
					<input id="" name="s" type="search"  placeholder="请输入搜索关键字" class="aui-header-search">
				</form>
			</div>
		</div>
		<a href="#" class="aui-header-item-icon">
			<i class="aui-icon aui-icon-packet" style="display:none"></i>
			<i class="aui-icon aui-icon-member" style="display:none"></i>
		</a>
	</header>
	<div style="display:block;height:2.8rem"></div>
	<!-- <div class="aui-scroll-content"> -->

				<?php

				foreach ($products as $product) {
						echo '<div class="am-g am-intro-bd">';
							echo '<a href="http://bdbbuy.com/mobile/ui-product.phtml?productId='.$product['product_id'].'">';
							#<img class="lazy" src="grey.gif" data-original="example.jpg" width="640" heigh="480">min-width: 72px; max-width: 100%; width: auto; height: auto;
								echo '<div class="am-intro-left am-u-sm-3">';
								echo '<div class="class_img_box"><img  class="lazy" src="./images/grey.gif" data-original="http://bdbbuy.com/media/catalog/product'.$product['image'].'" /></div>';
								echo '</div>';
									echo '<div class="am-intro-right am-u-sm-8">';
										echo '<h2>'.$product['name'].'</h2>';
										echo '<p>'.$product['short_description'];
										if (count($product['tier_price']) > 0) {
											$special_price = $product['tier_price'][0];
											echo '(';
											echo '购买'.round($special_price['price_qty'],0).'件低至$'.round($special_price['price'],2);
											echo ')';
										}
										echo '</p>';
										echo '<div class="text">';
											echo '<span class="fl">CA$&nbsp;&nbsp;'.round($product['price'], 2).'</span>';
											echo '<span class="fr"><img src="themes/img/icon/icon-kin.png" onclick="addToCart(\''.$cartId.'\',\''.$product['product_id'].'\')"/></span>';
										echo '</div>';
									echo '</div>';
								echo '</div>';
							echo '</a>';
						echo '</div>';
				}

				?>

		<div style="display:block;height:2.8rem"></div>
		<footer class="aui-footer-default aui-footer-fixed">
		<a href="index.phtml" class="aui-footer-item">
			<span class="aui-footer-item-icon aui-icon aui-footer-icon-home"></span>
			<span class="aui-footer-item-text">首页</span>
		</a>
		<a href="class.phtml" class="aui-footer-item">
			<span class="aui-footer-item-icon aui-icon aui-footer-icon-class"></span>
			<span class="aui-footer-item-text">分类</span>
<!-- 		</a>
	 		<a href="find.html" class="aui-footer-item">
			<span class="aui-footer-item-icon aui-icon aui-footer-icon-find"></span>
			<span class="aui-footer-item-text">发现</span>
		</a>  -->
		<a href="car.phtml" class="aui-footer-item">
			<span class="aui-footer-item-icon aui-icon aui-footer-icon-car"></span>
			<span class="aui-footer-item-text">购物车</span>
		</a>
		<?php
		include_once('./user.php');
		if (islogin()) {
			echo '<a href="ui-me.phtml" class="aui-footer-item">';
		}else
		{
			echo '<a href="login.html" class="aui-footer-item">';
		}
		?>
			<span class="aui-footer-item-icon aui-icon aui-footer-icon-me"></span>
			<span class="aui-footer-item-text">我的</span>
		</a>
	</footer>

<script type="text/javascript" src="themes/js/jquery.min.js"></script>
<script src="themes/js/aui.js"></script>
<script src="themes/js/jquery.lazyload.js"></script>
<script src="themes/js/jquery.scrollstop.js"></script>
<script  type="text/javascript">
	$(function(){
		$('img').lazyload({
			event: 'scrollstop'
		});
	});

</script>
</body>
</html>

