<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0"/>
	<meta name="apple-mobile-web-app-capable" content="yes"/>
	<meta name="apple-mobile-web-app-status-bar-style" content="black"/>
	<meta name="format-detection" content="telephone=no, email=no"/>
	<meta charset="UTF-8">
	<title>搜索结果</title>
	<link rel="stylesheet" href="themes/css/core.css">
	<link rel="stylesheet" href="themes/css/icon.css">
	<link rel="stylesheet" href="themes/css/home.css">
	<link rel="stylesheet" href="themes/css/add.css">
	<script src="themes/js/sweetalert2.js"></script>
	<link rel="stylesheet" href="themes/css/amazeui.min.css">
	<link rel="icon" type="image/x-icon" href="favicon.ico">
	<link href="iTunesArtwork@2x.png" sizes="114x114" rel="apple-touch-icon-precomposed">
</head>
<?php 
ini_set('display_errors',1);
include_once('./config.php');
include_once('./imagePathFix.php');
include_once('./user.php');
include_once('./cart.php');

$cartId = cartid();

$keyword=$_GET['s'];
$keywordtrim = str_replace(' ', '', $keyword);
$url=$baseHost . 'searchProduct.php?s='.$keywordtrim;
$products = json_decode(file_get_contents($url),true);

// xl add
$userinfo = userinfo();
$items = array();
foreach ($products as $p) {
	// 是否存在group_price
	$p['g_price'] = 0;

	$product_id = $p['product_id'];
	$url= $baseHost . 'productInfo.php?ids=' . $product_id;
	$jsonResult = json_decode(file_get_contents($url),true);
	if (count($jsonResult) > 0) {
		$product = $jsonResult[0];
		if (count($product['group_price'])>0) {
			foreach ($product['group_price'] as $key => $value) {  
			    if (!is_null($value['price'])) {
					$p['g_price'] = (float)$value['price'];
					break;
				}
			} 
		}
	}
	array_push($items, $p);
}
// xl add

?>



<body style="padding-left:10px;padding-right:10px">
	<header class="aui-header-default aui-header-fixed aui-header-bg">
		<a href="#" class="aui-header-item"  style="display:none">
			<i class="aui-icon aui-icon-code"></i>
		</a>
		<div class="aui-header-center aui-header-center-clear">
			<div class="aui-header-search-box">
				<i class="aui-icon aui-icon-small-search"></i>
				<form action="searchProduct.phtml" method="get">
					<input id="" name="s" type="search"  placeholder="请输入搜索关键字" class="aui-header-search">
				</form>
			</div>
		</div>
		<a href="#" class="aui-header-item-icon">
			<i class="aui-icon aui-icon-packet" style="display:none"></i>
			<i class="aui-icon aui-icon-member" style="display:none"></i>
		</a>
	</header>
	<div style="display:block;height:2.8rem"></div>


	<!-- <div class="aui-scroll-content"> -->

				<?php
				// include_once('./user.php');
				// $userinfo = userinfo();

				// echo 'hehe' . json_encode($userinfo);

				foreach ($items as $product) {
						echo '<div class="am-g am-intro-bd">';
							echo '<div class="am-intro-left am-u-sm-10">';
							echo '<a href="'. $baseHost .'ui-product.phtml?productId='.$product['product_id'].'">';
							#<img class="lazy" src="grey.gif" data-original="example.jpg" width="640" heigh="480">min-width: 72px; max-width: 100%; width: auto; height: auto;
								echo '<div class="am-intro-left am-u-sm-4">';
								echo '<div class="class_img_box"><img  class="lazy" src="./images/grey.gif" data-original="'.smallImage($product['image']).'" /></div>';
								echo '</div>';

								echo '<div class="am-intro-right am-u-sm-8"><div style="padding-left:10px;">';
									echo '<h2>'.$product['name'].'</h2>';
									echo '<p>'.$product['short_description'];
										if (count($product['tier_price']) > 0) {
											$special_price = $product['tier_price'][0];
											echo '(';
											echo '购买'.round($special_price['price_qty'],0).'件低至$'.round($special_price['price'],2);
											echo ')';
										}
									echo '</p>';
									echo '<div class="text">';
										// 批发价格
										if ( $userinfo != null && $userinfo['group_id'] == '2' && $product['g_price'] > 0 ) {
											echo '<span class="fl">CA$&nbsp;&nbsp;'.round($product['g_price'], 2).'</span>';	
										}else{
											// 特价显示
											if (!is_null($product['special_price'])) {
												echo '<span class="fl">CA$&nbsp;&nbsp;'.round($product['special_price'], 2).'</span>';	
												echo '<span class="aui-list-product-item-del-price">';
												echo 'CA$'.number_format($product['price'],2);
												echo '</span>	';
											}else{
												// 正常价格
												echo '<span class="fl">CA$&nbsp;&nbsp;'.round($product['price'], 2).'</span>';	
											}
										}

										// if (!is_null($product['special_price'])) {
										// 	echo '<span class="fl">CA$&nbsp;&nbsp;'.round($product['special_price'], 2).'</span>';	
										// 	echo '<span class="aui-list-product-item-del-price">';
										// 	echo 'CA$'.number_format($product['price'],2);
										// 	echo '</span>	';
										// }elseif(count($product['group_price']) > 0){ // xl add
										// 	$key = array_keys($product['group_price'])[0];
										// 	$test = $product['group_price'];
										// 	$price = $test[$key]['website_price'];
										// 	echo '<span class="fl">CA$&nbsp;&nbsp;'.round($price, 2).'</span>';
										// }else{
										// 	echo '<span class="fl">CA$&nbsp;&nbsp;'.round($product['price'], 2).'</span>';	
										// }
									echo '</div>';
								echo '</div></div>';
							echo '</a></div>';

							echo '<div class="am-intro-right am-u-sm-1" onclick="addToCart(\''.$cartId.'\',\''.$product['product_id'].'\')">';
							echo '<span class="fr add-to-car-button"><img src="themes/img/icon/icon-kin.png"/></span>';
							echo '</div>';
						echo '</div>';
				}

				?>

		<div style="display:block;height:2.8rem"></div>
		<footer class="aui-footer-default aui-footer-fixed">
		<a href="index.phtml" class="aui-footer-item">
			<span class="aui-footer-item-icon aui-icon aui-footer-icon-home"></span>
			<span class="aui-footer-item-text">首页</span>
		</a>
		<a href="class.phtml" class="aui-footer-item">
			<span class="aui-footer-item-icon aui-icon aui-footer-icon-class"></span>
			<span class="aui-footer-item-text">分类</span>
<!-- 		</a>
	 		<a href="find.html" class="aui-footer-item">
			<span class="aui-footer-item-icon aui-icon aui-footer-icon-find"></span>
			<span class="aui-footer-item-text">发现</span>
		</a>  -->
		<a href="car.phtml" class="aui-footer-item">
			<span class="aui-footer-item-icon aui-icon aui-footer-icon-car"></span>
			<span class="aui-footer-item-text">购物车</span>
		</a>
		<?php
		include_once('./user.php');
		if (islogin()) {
			echo '<a href="ui-me.phtml" class="aui-footer-item">';
		}else
		{
			echo '<a href="login.html" class="aui-footer-item">';
		}
		?>
			<span class="aui-footer-item-icon aui-icon aui-footer-icon-me"></span>
			<span class="aui-footer-item-text">我的</span>
		</a>
	</footer>

<script type="text/javascript" src="themes/js/jquery.min.js"></script>
<script src="themes/js/aui.js"></script>
<script src="themes/js/jquery.lazyload.js"></script>
<script src="themes/js/jquery.scrollstop.js"></script>
<script  type="text/javascript">
	function addToCart(cartId,productId) { 

		swal({
			  title: "",
			  text: "正在添加",
			  onOpen:()=>{swal.showLoading()}
			});

        $.ajax({  

            url:"<?php echo $baseHost; ?>cart.php?addToCart="+cartId+"&productId="+productId,           

            type: "GET",         

            success:function(result){  
            	if (result != "true") {
					swal({
					  // position: 'top-end',
					  type: 'error',
					  title: '加入失败',
					  showConfirmButton: false,
					  timer: 1500
					})
            	}else{
					swal({
					  // position: 'top-end',
					  type: 'success',
					  title: '加入成功',
					  showConfirmButton: false,
					  timer: 1500
					})
            	};

            },

            error:function(XMLHttpRequest, textStatus, errorThrown){
            		swal({
					  title: "",
					  text: "加入失败",
					  icon: "error",
					  button: false,
					  timer: 1300,
					});
                // $('#loading').hideLoading();

            }

        });

    }
	$(function(){
		$('img').lazyload({
			event: 'scrollstop'
		});
		$(window).scroll(function() {
			$('img').lazyload({
				event: 'scrollstop'
			});
		});
	});

</script>
</body>
</html>

