<!DOCTYPE html>
<?php

?>
<html>
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no, minimal-ui"/>
	<meta name="apple-mobile-web-app-capable" content="yes"/>
	<meta name="apple-mobile-web-app-status-bar-style" content="black"/>
	<meta name="format-detection" content="telephone=no, email=no"/>
	<meta charset="UTF-8">
	<title>个人中心</title>
	<link rel="stylesheet" href="themes/css/core.css">
	<link rel="stylesheet" href="themes/css/icon.css">
	<link rel="stylesheet" href="themes/css/home.css">
	<link rel="icon" type="image/x-icon" href="favicon.ico">
	<link href="iTunesArtwork@2x.png" sizes="114x114" rel="apple-touch-icon-precomposed">
</head>
<body style="background:#fc0f42">
	<header class="aui-header-default aui-header-fixed aui-header-bg">
		<a href="#" class="aui-header-item">
			<!--<i class="aui-icon aui-icon-back-white" id="scrollSearchI" style="display:block"></i>-->
			<div id="scrollSearchDiv">
				<img src="themes/img/user/head-3.jpg" alt="">
			</div>
		</a>
		<div class="aui-header-center aui-header-center-clear">
			<div class="">

			</div>
		</div>
		<a href="my-set.html" class="aui-header-item-icon">
			<i class="aui-icon aui-icon-Set"></i>
		</a>
	</header>

	<section class="aui-me-content">
		<div class="aui-me-content-box">
			<div class="aui-me-content-info"></div>
			<div class="aui-me-content-list">
				<div class="aui-me-content-item">
					<div class="aui-me-content-item-head">
						<div class="aui-me-content-item-img">
							<img src="images/welcome.png" alt="">
						</div>
						<div class="aui-me-content-item-title" id="username"></div>
					</div>
					<!-- <div class="aui-me-content-item-text">
						<a class ="aui-me-content-item-a" href="my-orders.html">
							<span>98</span>
							<span>收藏</span>
						</a>
						<a class ="aui-me-content-item-a" href="my-orders.html">
							<span>99</span>
							<span>足迹</span>
						</a>
						<a class ="aui-me-content-item-a" href="my-orders.html">
							<span>65</span>
							<span>积分</span>
						</a>
					</div> -->
				</div>
				<!-- <div class="aui-me-content-card">
					<h3><i class="aui-icon aui-card-me"></i>铂金会员</h3>
					<a href="my-membership.html">点击查看特权</a>
				</div> -->
			</div>
		</div>
		<div class="aui-me-content-order">
			<a href="my-order.phtml" class="aui-well aui-fl-arrow">
				<div class="aui-well-bd">我的订单</div>
				<div class="aui-well-ft">查看全部</div>
			</a>
		</div>
		<section class="aui-grid-content">
			<div class="aui-grid-row">
				<a href="my-order.phtml" class="aui-grid-row-item">
					<i class="aui-icon-large aui-icon-large-sm aui-icon-wallet"></i>
					<p class="aui-grid-row-label">待付款</p>
				</a>
				<a href="my-order.phtml" class="aui-grid-row-item">
					<i class="aui-icon-large aui-icon-large-sm aui-icon-goods"></i>
					<p class="aui-grid-row-label">待发货</p>
				</a>
				<a href="my-order.phtml" class="aui-grid-row-item">
					<i class="aui-icon-large aui-icon-large-sm aui-icon-receipt"></i>
					<p class="aui-grid-row-label">待收货</p>
				</a>
				<a href="my-order.phtml" class="aui-grid-row-item">
					<i class="aui-icon-large aui-icon-large-sm aui-icon-evaluate"></i>
					<p class="aui-grid-row-label">待评价</p>
				</a>
				<a href="my-order.phtml" class="aui-grid-row-item">
					<i class="aui-icon-large aui-icon-large-sm aui-icon-refund"></i>
					<p class="aui-grid-row-label">退货退款</p>
				</a>
			</div>
			<div class="aui-dri"></div>
			<div class="aui-me-content-order">
				<a href="#" class="aui-well ">
					<div class="aui-well-bd">我的服务</div>
					<!--<div class="aui-well-ft">查看全部</div>-->
				</a>
			</div>
			<div class="aui-grid-row">
				<a href="shippingarea.html" class="aui-grid-row-item">
					<i class="aui-icon-large aui-icon-large-sm aui-icon-help"></i>
					<p class="aui-grid-row-label">配送规则</p>
				</a>
				<!-- <a href="#" class="aui-grid-row-item">
					<i class="aui-icon-large aui-icon-large-sm aui-icon-help"></i>
					<p class="aui-grid-row-label">帮助中心</p>
				</a> -->
				<!-- <a href="my-invitation.html" class="aui-grid-row-item">
					<i class="aui-icon-large aui-icon-large-sm aui-icon-invitation"></i>
					<p class="aui-grid-row-label">邀请好友</p>
				</a>
				<a href="my-coupon.html" class="aui-grid-row-item">
					<i class="aui-icon-large aui-icon-large-sm aui-icon-coupon"></i>
					<p class="aui-grid-row-label">优惠券</p>
				</a>
				<a href="my-sign.html" class="aui-grid-row-item">
					<i class="aui-icon-large aui-icon-large-sm aui-icon-signs"></i>
					<p class="aui-grid-row-label">签到领币</p>
				</a>
				<a href="my-purchase.html" class="aui-grid-row-item">
					<i class="aui-icon-large aui-icon-large-sm aui-icon-fight"></i>
					<p class="aui-grid-row-label">我的拼团</p>
				</a>
				<a href="my-hands.html" class="aui-grid-row-item">
					<i class="aui-icon-large aui-icon-large-sm aui-icon-recommend"></i>
					<p class="aui-grid-row-label">商品推手</p>
				</a>
				<a href="#" class="aui-grid-row-item">
					<i class="aui-icon-large aui-icon-large-sm aui-icon-recharge"></i>
					<p class="aui-grid-row-label">充值中心</p>
				</a>
				<a href="#" class="aui-grid-row-item">
					<i class="aui-icon-large aui-icon-large-sm aui-icon-problem"></i>
					<p class="aui-grid-row-label">我的问答</p>
				</a>
				<a href="#" class="aui-grid-row-item">
					<i class="aui-icon-large aui-icon-large-sm aui-icon-evaluates"></i>
					<p class="aui-grid-row-label">我的评价</p>
				</a>
				<a href="#" class="aui-grid-row-item">
					<i class="aui-icon-large aui-icon-large-sm aui-icon-shares"></i>
					<p class="aui-grid-row-label">我的分享</p>
				</a> -->
			</div>
			<div class="aui-recommend">
				<img src="themes/img/bg/icon-tj3.jpg" alt="">
				<!--<h2>为你推荐</h2>-->
			</div>
			<section class="aui-list-product">
				<div class="aui-list-product-box"  id = "recommend">
					<!-- <a href="ui-product.phtml" class="aui-list-product-item">
						<div class="aui-list-product-item-img">
							<img src="themes/img/pd/sf-15.jpg" alt="">
						</div>
						<div class="aui-list-product-item-text">
							<h3>KOBE LETTUCE 秋冬新款 女士日系甜美纯色半高领宽松套头毛衣针织衫</h3>
							<div class="aui-list-product-mes-box">
								<div>
							<span class="aui-list-product-item-price">
								<em>¥</em>
								399.99
							</span>
									<span class="aui-list-product-item-del-price">
								¥495.65
							</span>
								</div>
								<div class="aui-comment">986评论</div>
							</div>
						</div>
					</a> -->
				</div>
			</section>
		</section>
	<?php
	include_once('./user.php');
	if (islogin()) {
		echo '<div class="aui-out">';
		echo '<a class="red-color" style="color:#fff" onclick="logout()">退出登录</a>';
		echo '</div>';
	}else
	{
		echo '<script type="text/javascript">';
		echo 'window.location.href="http://bdbbuy.com/mobile/index.phtml";';
		echo '</script>';
	}
	?>
	</section>



	<footer class="aui-footer-default aui-footer-fixed">
		<a href="index.phtml" class="aui-footer-item">
			<span class="aui-footer-item-icon aui-icon aui-footer-icon-home"></span>
			<span class="aui-footer-item-text">首页</span>
		</a>
		<a href="class.phtml" class="aui-footer-item">
			<span class="aui-footer-item-icon aui-icon aui-footer-icon-class"></span>
			<span class="aui-footer-item-text">分类</span>
		</a>
<!-- 		<a href="find.html" class="aui-footer-item">
			<span class="aui-footer-item-icon aui-icon aui-footer-icon-find"></span>
			<span class="aui-footer-item-text">发现</span>
		</a> -->
		<a href="car.phtml" class="aui-footer-item">
			<span class="aui-footer-item-icon aui-icon aui-footer-icon-car"></span>
			<span class="aui-footer-item-text">购物车</span>
		</a>
		<a href="ui-me.phtml" class="aui-footer-item aui-footer-active">
			<span class="aui-footer-item-icon aui-icon aui-footer-icon-me"></span>
			<span class="aui-footer-item-text">我的</span>
		</a>
	</footer>

	<script type="text/javascript" src="themes/js/jquery.min.js"></script>
	<script type="text/javascript">
        $(function () {
            //绑定滚动条事件
            $(window).bind("scroll", function () {
                var sTop = $(window).scrollTop();
                var sTop = parseInt(sTop);
                if (sTop >= 44) {
                    if (!$("#scrollSearchDiv").is(":visible")) {
                        try {
                            $("#scrollSearchDiv").slideDown();
                        } catch (e) {
                            $("#scrollSearchDiv").show();
                        }
                    }
                }
                else {
                    if ($("#scrollSearchDiv").is(":visible")) {
                        try {
                            $("#scrollSearchDiv").slideUp();
                        } catch (e) {
                            $("#scrollSearchDiv").hide();
                        }
                    }
                }
            });

            // 请求精选推荐商品信息
			recommend_lists = ['5686', '5689', '5692', '5790', '5826', '5838', '5856', '5862', '5880', '5884', '5886', '5892'];
			ids = recommend_lists.join('-');
			$.get('http://bdbbuy.com/mobile/productInfo.php?ids=' + ids, function(data){
				var results = eval("(" + data + ")");
				// console.log(results);
				for(var i = 0; i < results.length; i ++){
					var res = results[i];
					var id = res['product_id'];
					var name = res['name'];
					var price = res['price'];
					var url = 'http://bdbbuy.com/media/catalog/product' + res['image'];
					var str = '<a href="ui-product.phtml?productId='+id+'" class="aui-list-product-item"><div class="aui-list-product-item-img"><img src="' + url + '" alt=""></div><div class="aui-list-product-item-text"><h3>' + name + '</h3><div class="aui-list-product-mes-box"><div><span class="aui-list-product-item-price"><em>CA$</em>' + price.substr(0,price.indexOf(".")+3) + '</span></div></div></div></a>';
					//<span class="aui-list-product-item-del-price"><em>$</em>' + special_price + '</span>
					$("#recommend").append(str);
				}
			});

			document.getElementById("username").innerHTML=getCookie('bdb-nn');
        });
		//读取cookies 
		function getCookie(name) 
		{ 
			var arr,reg=new RegExp("(^| )"+name+"=([^;]*)(;|$)");

			if(arr=document.cookie.match(reg))

			    return unescape(arr[2]); 
			else 
			    return null; 
		} 

		//删除cookies 
		function delCookie(name) 
		{ 
			var exp = new Date(); 
			exp.setTime(exp.getTime() - 1); 
			var cval=getCookie(name); 
			if(cval!=null) 
			    document.cookie= name + "="+cval+";expires="+exp.toGMTString(); 
		}

		function logout(){
       		window.location.href='http://bdbbuy.com/mobile/index.phtml';
       		delCookie('bdb-ui');
       		delCookie('bdb-nn');
		}
	</script>
</body>
</html>